import type { Language } from './types'

export type Phase = 1 | 2 | 3

export interface GameDef {
  id: string
  name: string
  nameHi?: string
  nameAs?: string
  nameBn?: string
  nameBrx?: string
  nameMni?: string
  phase: Phase
  domain: string
  cultural: string
  culturalHi?: string
  culturalBn?: string
  culturalBrx?: string
  principle: string
  glyph: string
  instructionKey: string
  minDifficulty: number
  estimatedMins?: number
}

export const GAMES: GameDef[] = [
  // Phase 1: Familiarization, Episodic & Auditory Recognition
  {
    id: 'faces',
    name: 'Faces of Home',
    nameHi: 'घर के अपने चेहरे',
    nameAs: 'ঘৰৰ চিনাকী মুখবোৰ',
    nameBn: 'ঘরের চেনা মুখ',
    nameBrx: "न'नि सानजायना मुख",
    nameMni: 'ইমুংগী মী',
    phase: 1,
    domain: 'Family & Caregiver Recognition',
    cultural: 'Caregiver photos & regional Northeast family avatars',
    culturalBn: 'পরিচর্যাকারীর ছবি ও উত্তর-পূর্বের পরিবারের চেনা অবতার',
    culturalBrx: "मावथाइ थाग्रानि फोटो आरो उत्तर-पूर्वनि न'नि सिनायथि अवतार",
    principle: 'Spaced Retrieval Therapy (SRT)',
    glyph: '👪',
    instructionKey: 'g_faces_intro',
    minDifficulty: 0,
    estimatedMins: 3,
  },
  {
    id: 'melodies',
    name: 'Morning Melodies',
    nameHi: 'सुबह की धुनें (पारंपरिक वाद्य)',
    nameAs: 'ৰাতিপুৱাৰ সুৰ',
    nameBn: 'সকালের সুর (ঐতিহ্যবাহী বাদ্যযন্ত্র)',
    nameBrx: 'फुंनि राव (जों रावग्रा)',
    nameMni: 'অয়ুক্কী সুর',
    phase: 1,
    domain: 'Auditory & Instrument Recognition',
    cultural: '40+ instruments from Assam, Meghalaya, Manipur, Mizoram, Nagaland, Tripura, Arunachal, Sikkim & India',
    culturalBn: 'অসম, মেঘালয়, মণিপুর, মিজোরাম, নাগাল্যান্ড, ত্রিপুরা, অরুণাচল ও সিকিমের ৪০টির বেশি বাদ্যযন্ত্র',
    culturalBrx: 'आसाम, मेघालय, मणिपुर, मिजोराम, नागालैंड, त्रिपुरा, अरुणाचल आरो सिक्किमनि ४० बांद्रा जों रावग्रा',
    principle: 'Auditory discrimination & errorless cues',
    glyph: '🪘',
    instructionKey: 'g_melodies_intro',
    minDifficulty: 0,
    estimatedMins: 4,
  },
  {
    id: 'objects',
    name: 'Familiar Objects',
    nameHi: 'पहचानी वस्तुएं (घर-आँगन की चीज़ें)',
    nameAs: 'চিনাকী ঘৰুৱা বস্তু',
    nameBn: 'চেনা ঘরের জিনিস',
    nameBrx: "सिनायथि न'नि जोंफोर",
    nameMni: 'য়ুমগী পোৎলম',
    phase: 1,
    domain: 'Semantic & Object Recognition',
    cultural: 'Tamol cutter, Japi hat, brass handi, clay teapot, tea plucking basket',
    culturalBn: 'তামোল কাটার, জাপি টুপি, পিতলের হাঁড়ি, মাটির চায়ের পাত্র ও চা তোলার ঝুড়ি',
    culturalBrx: 'तमोल खाटार, जापि हाट, पितलनि हांड़ि, माटिनि चाहनि पात्र आरो चाह लानाय बास्केट',
    principle: 'Functional & episodic semantic memory',
    glyph: '🧺',
    instructionKey: 'g_objects_intro',
    minDifficulty: 0,
    estimatedMins: 3,
  },
  {
    id: 'tray',
    name: 'Memory Tray',
    nameHi: 'स्मृति थाली (ट्रे की वस्तुएं)',
    nameAs: 'স্মৃতিৰ কাঁহী',
    nameBn: 'স্মৃতির থালা',
    nameBrx: 'गोसोखां थालि',
    nameMni: 'নিংসিংশিংগী থালী',
    phase: 1,
    domain: 'Visual Working Memory',
    cultural: 'Kim’s game with morning tea, harvest fruits, flowers & kitchen spices',
    culturalBn: 'সকালের চা, ফসলের ফল, ফুল ও রান্নাঘরের মশলা নিয়ে স্মৃতির খেলা',
    culturalBrx: 'फुंनि चाह, फसलनि फल, फुल आरो सुस्रा मस्लाजों गोसोखां खेला',
    principle: 'Short-term visual retention with gentle reveal',
    glyph: '🍱',
    instructionKey: 'g_tray_intro',
    minDifficulty: 0,
    estimatedMins: 4,
  },
  {
    id: 'sequence',
    name: 'Daily Life Sequence',
    nameHi: 'रोज़मर्रा का क्रम (दिनचर्या)',
    nameAs: 'দৈনন্দিন জীৱনৰ ক্ৰম',
    nameBn: 'দৈনন্দিন জীবনের ক্রম',
    nameBrx: 'दिनि हाबानि सोलों',
    nameMni: 'নুমিৎ খুদিংগী থবক',
    phase: 1,
    domain: 'Executive Function & Sequencing',
    cultural: 'Morning tea, cooking rice, tamol preparation, harvest & evening prayer',
    culturalBn: 'সকালের চা, ভাত রান্না, তামোল তৈরি, ফসল কাটা ও সন্ধ্যার প্রার্থনা',
    culturalBrx: 'फुंनि चाह, भात सोरजोनाय, तमोल बानाय, फसल लानाय आरो बेलासिनि मोनाजों',
    principle: 'Errorless learning — slots snap into order',
    glyph: '🫖',
    instructionKey: 'g_sequence_intro',
    minDifficulty: 0,
    estimatedMins: 4,
  },
  {
    id: 'foods',
    name: 'Traditional Foods & Harvest',
    nameHi: 'पारंपरिक खान-पान और फल',
    nameAs: 'পৰম্পৰাগত খাদ্য আৰু ফল',
    nameBn: 'ঐতিহ্যবাহী খাবার ও ফসল',
    nameBrx: 'रंजानि जानाय आरो फसल',
    nameMni: 'চানবা-থকপগী পোৎ',
    phase: 1,
    domain: 'Semantic Memory & Food Recognition',
    cultural: 'Pitha, Khar, Black rice kheer, Singju, Bai, Momos, Thukpa & mountain citrus',
    culturalBn: 'পিঠা, খার, কালো চালের পায়েস, সিঙজু, বাই, মোমো, থুকপা ও পাহাড়ি লেবু',
    culturalBrx: 'पिठा, खार, गोमो बोरोनि पायेस, सिंगजु, बाइ, मोमो, थुकपा आरो हाजोंनि लेबु',
    principle: 'Reminiscence & cultural recognition',
    glyph: '🍲',
    instructionKey: 'g_foods_intro',
    minDifficulty: 0,
    estimatedMins: 3,
  },
  {
    id: 'pairs',
    name: 'Orchid Pairs',
    nameHi: 'ऑर्किड और फूलों की जोड़ियाँ',
    nameAs: 'ফুলৰ যোৰা মিলাওক',
    nameBn: 'অর্কিডের জোড়া',
    nameBrx: 'अर्किडनि जोर',
    nameMni: 'লৈগী যোড়া',
    phase: 1,
    domain: 'Working Memory & Concentration',
    cultural: 'Native Himalayan orchids, lotus & harvest fruits',
    culturalBn: 'হিমালয়ের অর্কিড, পদ্ম ও ফসলের ফল',
    culturalBrx: 'हिमालयनि अर्किड, कमल आरो फसलनि फल',
    principle: 'Cognitive Stimulation Therapy (CST)',
    glyph: '🪷',
    instructionKey: 'g_pairs_intro',
    minDifficulty: 0,
    estimatedMins: 3,
  },
  {
    id: 'sounds',
    name: 'Village & Nature Sounds',
    nameHi: 'गाँव और प्रकृति की आवाज़ें',
    nameAs: 'গাঁৱৰ আৰু প্ৰকৃতিৰ মাত',
    nameBn: 'গ্রাম ও প্রকৃতির শব্দ',
    nameBrx: 'नोङोनी आरो प्रकृतिनि राव',
    nameMni: 'খুঙ্গংগী খোঞ্জেল',
    phase: 1,
    domain: 'Auditory Processing & Nature Cues',
    cultural: 'Monsoon rain, mountain river, rooster, cuckoo, evening temple bell, steaming kettle',
    culturalBn: 'বর্ষার বৃষ্টি, পাহাড়ি নদী, মোরগ, কোকিল, মন্দিরের ঘণ্টা ও ফুটন্ত কেটলি',
    culturalBrx: 'बर्खानि हाखोर, हाजोंनि दै, फुंनि फोरों, कुकु, बेलासिनि मन्दिर घन्टा आरो फुदुं केटलि',
    principle: 'Audio-first recognition with zero reading needed',
    glyph: '🔔',
    instructionKey: 'g_sounds_intro',
    minDifficulty: 0,
    estimatedMins: 3,
  },

  // Phase 2: Targeted Cognitive Training, Visual Search, Patterns
  {
    id: 'places',
    name: 'Northeast Places & Nature',
    nameHi: 'पूर्वोत्तर के सुंदर स्थल',
    nameAs: 'উত্তৰ-পূবৰ চিনাকী ঠাই',
    nameBn: 'উত্তর-পূর্বের স্থান ও প্রকৃতি',
    nameBrx: 'उत्तर-पूर्वनि जायगा आरो प्रकृति',
    nameMni: 'অৱাং নোংপোক্কী মফমশিং',
    phase: 2,
    domain: 'Visuospatial & Environmental Recognition',
    cultural: 'Living root bridges, Kaziranga, Loktak lake, tea estates, Tawang monastery',
    culturalBn: 'জীবন্ত শিকড়ের সেতু, কাজিরাঙা, লোকটাক হ্রদ, চা-বাগান ও তাওয়াং মঠ',
    culturalBrx: 'जिउनि सोमोन्दो सेतु, काजिरांगा, लोकटाक हाग्रा, चाह बागान आरो तवाङ मठ',
    principle: 'Gentle landmark association & visual orientation',
    glyph: '🏞️',
    instructionKey: 'g_places_intro',
    minDifficulty: 0,
    estimatedMins: 4,
  },
  {
    id: 'loom',
    name: "Weaver's Loom & Motifs",
    nameHi: 'बुनकर की खड़िया और नमूने',
    nameAs: 'তাঁতশালৰ ফুল',
    nameBn: 'তাঁতির তাঁত ও নকশা',
    nameBrx: 'बुनायनि तांत आरो नक्सा',
    nameMni: 'য়োংখামগী মচেৎ',
    phase: 2,
    domain: 'Pattern Completion & Visual Attention',
    cultural: 'Gamosa red motifs, Naga shawl bands, Mizo Puan stripes, Manipuri Phanek',
    culturalBn: 'গামছার লাল নকশা, নাগা শালের দাগ, মিজো পুয়ানের রেখা ও মণিপুরি ফানেক',
    culturalBrx: 'गामोसा सोर नक्सा, नागा सालनि दाग, मिजो पुआननि दाग आरो मणिपुरी फानेक',
    culturalHi: 'गोमósा लाल नमूने, नागा शॉल पट्टी, मizo पुआन धरा, मणिपुरी फनेक',
    principle: 'Cognitive pattern recognition & inductive reasoning',
    glyph: '🧶',
    instructionKey: 'g_loom_intro',
    minDifficulty: 0,
    estimatedMins: 4,
  },
  {
    id: 'picture',
    name: 'Picture Memory (Scene Recall)',
    nameHi: 'दृश्य स्मृति (तस्वीर के सवाल)',
    nameAs: 'ছবিৰ স্মৃতি পৰীক্ষা',
    nameBn: 'ছবির স্মৃতি (দৃশ্য মনে করা)',
    nameBrx: 'सोदोबनि गोसोखां (फोटोनि सोंथाइ)',
    nameMni: 'ফোতো নিংশিংবা',
    phase: 2,
    domain: 'Short-term Visual Observation',
    cultural: 'Bihu courtyard, tea harvest lawn, kitchen veranda, river ferry ghat',
    culturalBn: 'বিহুর উঠোন, চা-ফসলের মাঠ, রান্নাঘরের বারান্দা ও নদীর ঘাট',
    culturalBrx: 'बिहुनि आंगना, चाह फसलनि हाजों, सुस्रानि बरान्दा आरो दैनि घाट',
    principle: 'Delayed visual recall & detail attention',
    glyph: '🖼️',
    instructionKey: 'g_picture_intro',
    minDifficulty: 0,
    estimatedMins: 4,
  },
  {
    id: 'bamboo',
    name: 'Category Sorting (Bamboo Baskets)',
    nameHi: 'सही टोकरी में छँटाई (वर्गीकरण)',
    nameAs: 'সাঁচ বাছনি আৰু থাপনা',
    nameBn: 'বাঁশের ঝুড়িতে সাজানো',
    nameBrx: 'बांसनि साजाय आरो बासाय',
    nameMni: 'পোৎলম খায়দোকপা',
    phase: 2,
    domain: 'Categorization & Cognitive Flexibility',
    cultural: 'Sorting fruits, forest animals, tools, handloom textiles & flowers',
    culturalBn: 'ফল, বনের প্রাণী, সরঞ্জাম, তাঁতের কাপড় ও ফুল সাজানো',
    culturalBrx: 'फल, जंगलनि जिबफोर, हांखो, हांथतांतनि फराय आरो फुल बासाय',
    culturalHi: 'फल, जंगल के जानवर, औजार, हथकरघा वस्त्र और फूलों की छँटाई',
    principle: 'Semantic categorization & sorting',
    glyph: '🧺',
    instructionKey: 'g_bamboo_intro',
    minDifficulty: 0,
    estimatedMins: 3,
  },
  {
    id: 'phrases',
    name: 'Familiar Proverbs & Expressions',
    nameHi: 'कहावतें और मीठी बातें',
    nameAs: 'ফকৰা-যোজনা আৰু বাক্য',
    nameBn: 'চেনা প্রবাদ ও কথা',
    nameBrx: 'सिनायथि बाथ्रा आरो बिबुं',
    nameMni: 'পাৱারুক অমশুং ৱাখল্লোন',
    phase: 2,
    domain: 'Verbal Association & Reminiscence',
    cultural: 'Hospitality sayings, tea plucking rhymes, farmer proverbs, folk wisdom',
    culturalBn: 'আতিথেয়তার কথা, চা তোলার ছড়া, কৃষকের প্রবাদ ও লোকজ জ্ঞান',
    culturalBrx: 'सुबुंनो मोजां बाथ्रा, चाह लानाय छन्दा, हाबग्रानि बिबुं आरो लोकनि सोलों',
    principle: 'Verbal completion & semantic retrieval',
    glyph: '📜',
    instructionKey: 'g_phrases_intro',
    minDifficulty: 0,
    estimatedMins: 3,
  },
  {
    id: 'safari',
    name: 'Wildlife Safari',
    nameHi: 'वन्यजीव सैर (जंगल के मित्र)',
    nameAs: 'বন্যপ্ৰাণীৰ সন্ধান',
    nameBn: 'বন্যপ্রাণী ভ্রমণ',
    nameBrx: 'जंगलनि जिबफोर सान',
    nameMni: 'উমংগী শাশিং',
    phase: 2,
    domain: 'Visual Search & Concentration',
    cultural: 'One-horned Rhino, Hornbill, Mithun, Asian Elephant, Peacock in Kaziranga',
    culturalBn: 'কাজিরাঙার একশৃঙ্গ গণ্ডার, ধনেশ, মিথুন, হাতি ও ময়ূর',
    culturalBrx: 'काजिरांगानि एसे सिङनि गोराय, हार्नबिल, मिथुन, हाथि आरो मयूर',
    principle: 'Figure-ground discrimination in natural scenes',
    glyph: '🦏',
    instructionKey: 'g_safari_intro',
    minDifficulty: 0,
    estimatedMins: 4,
  },
  {
    id: 'cheraw',
    name: 'Cheraw Bamboo Steps',
    nameHi: 'छेराव की ताल (मिज़ो बांस नृत्य)',
    nameAs: 'চেৰাও বাঁহৰ নৃত্য',
    nameBn: 'চেরাও বাঁশের পদক্ষেপ',
    nameBrx: 'चेराव बांसनि थाखो',
    nameMni: 'চেৰাও ডান্স',
    phase: 2,
    domain: 'Rhythmic Attention & Timing',
    cultural: 'Mizo Cheraw rhythmic bamboo dance',
    culturalBn: 'মিজো চেরাওয়ের তালময় বাঁশের নাচ',
    culturalBrx: 'मिजो चेरावनि तालनि बांस नाच',
    culturalHi: 'मिज़ो छेराव लयबद्ध बांस नर्तन',
    principle: 'Sustained timing & motor synchronization',
    glyph: '🥢',
    instructionKey: 'g_cheraw_intro',
    minDifficulty: 0,
    estimatedMins: 3,
  },
  {
    id: 'spot',
    name: 'Spot the Difference',
    nameHi: 'फर्क पहचानो (सजग दृष्टि)',
    nameAs: 'পাৰ্থক্য বিচাৰক',
    nameBn: 'তফাত খুঁজুন',
    nameBrx: 'फरायथि नाय',
    nameMni: 'খেৎনবা য়েংবা',
    phase: 2,
    domain: 'Selective Visual Attention',
    cultural: 'Tea estate mornings, Bihu courtyard & river landing scenes',
    culturalBn: 'চা-বাগানের সকাল, বিহুর উঠোন ও নদীর ঘাটের দৃশ্য',
    culturalBrx: 'चाह बागाननि फुं, बिहुनि आंगना आरो दैनि घाटनि नुजाथाइ',
    culturalHi: 'चाय बागান की सुबह, बिहु आंगन और नदी किनारे के दृश्य',
    principle: 'Visual discrimination & focus',
    glyph: '🔍',
    instructionKey: 'g_spot_intro',
    minDifficulty: 0,
    estimatedMins: 3,
  },
  {
    id: 'oddone',
    name: 'Odd One Out',
    nameHi: 'अलग क्या है? (विषम पहचान)',
    nameAs: 'অমিলটো বাছক',
    nameBn: 'আলাদা কোনটি',
    nameBrx: 'जेया मिलाखै',
    nameMni: 'তোঙানবা পোৎলম',
    phase: 2,
    domain: 'Categorization & Semantic Association',
    cultural: 'Traditional foods, garden flowers, kitchen tools & river animals',
    culturalBn: 'ঐতিহ্যবাহী খাবার, বাগানের ফুল, রান্নাঘরের সরঞ্জাম ও নদীর প্রাণী',
    culturalBrx: 'रंजानि जानाय, बागाननि फुल, सुस्रानि हांखो आरो दैनि जिबफोर',
    culturalHi: 'पारंपरिक भोजन, बागीचे के फूल, रसोई के बर्तन और नदी के जीव',
    principle: 'Cognitive Stimulation Therapy (CST) — semantic categorization',
    glyph: '🎯',
    instructionKey: 'g_oddone_intro',
    minDifficulty: 0,
    estimatedMins: 3,
  },
  {
    id: 'word',
    name: 'Word Harvest',
    nameHi: 'शब्दों की फ़सल (वर्ग शब्द)',
    nameAs: 'শব্দৰ শস্য',
    nameBn: 'শব্দের ফসল',
    nameBrx: 'बाथ्रानि फसल',
    nameMni: 'ৱাহৈ খোমজিনবা',
    phase: 2,
    domain: 'Verbal Fluency & Semantic Recall',
    cultural: 'Market harvest, festival customs, weaving terms & village life',
    culturalBn: 'বাজারের ফসল, উৎসবের রীতি, তাঁতের শব্দ ও গ্রামের জীবন',
    culturalBrx: 'बजारनि फसल, कुमुसिनि नेम, बुनायनि बाथ्रा आरो गामनि जिउ',
    culturalHi: 'बाज़ार की फ़सल, त्योहारों के रीति-रिवाज़ और गाँव का जीवन',
    principle: 'Computerized cognitive training on verbal associations',
    glyph: '🌾',
    instructionKey: 'g_word_intro',
    minDifficulty: 0,
    estimatedMins: 3,
  },

  // Phase 3: Reminiscence, Calculation, Emotional Wellbeing
  {
    id: 'market',
    name: 'Market Day (Village Haat)',
    nameHi: 'बाज़ार का दिन (हाट में खरीदारी)',
    nameAs: 'হাঁট-বজাৰৰ দিন',
    nameBn: 'বাজারের দিন (গ্রামের হাট)',
    nameBrx: 'बजारनि दिन (गामनि हाट)',
    nameMni: 'কৈথেল নুমিৎ',
    phase: 3,
    domain: 'Working Memory & Budgeting',
    cultural: 'Friendly local bazaar with fish, honey, seasonal vegetables & wicker baskets',
    culturalBn: 'মাছ, মধু, ঋতুর সবজি ও বাঁশের ঝুড়ি নিয়ে গ্রামের হাট',
    culturalBrx: 'मै, मधु, समनि सोरजिनाय सब्जि आरो बांसनि झुरिजों गामनि हाट',
    principle: 'Anxiety-free everyday calculation & planning',
    glyph: '🛒',
    instructionKey: 'g_market_intro',
    minDifficulty: 0,
    estimatedMins: 4,
  },
  {
    id: 'teawalk',
    name: 'Tea Garden Walk',
    nameHi: 'चाय बागान की सैर',
    nameAs: 'চাহ বাগিচাৰ খোজ',
    nameBn: 'চা-বাগানের পথে হাঁটা',
    nameBrx: 'चाह बागाननि खोंसे',
    nameMni: 'চা পামগী খোঙচৎ',
    phase: 3,
    domain: 'Visuospatial Path Navigation',
    cultural: 'Paved paths through rolling Assam tea hills',
    culturalBn: 'অসমের ঢেউখেলানো চা-পাহাড়ের পাকা পথ',
    culturalBrx: 'आसामनि हाबाय हाबाय जाहोनाय चाह हाजोंनि सोलों',
    principle: 'Gentle step tracing & leaf collection',
    glyph: '🍃',
    instructionKey: 'g_teawalk_intro',
    minDifficulty: 0,
    estimatedMins: 3,
  },
  {
    id: 'tales',
    name: 'Festival Tales & Folklore',
    nameHi: 'त्योहारों की सुंदर कहानियाँ',
    nameAs: 'উৎসৱৰ সাধুকথা',
    nameBn: 'উৎসবের গল্প ও লোককথা',
    nameBrx: 'कुमुसि बाथ्रा आरो लोककथा',
    nameMni: 'ৱারী অমশুং পুৱারী',
    phase: 3,
    domain: 'Verbal Memory & Reminiscence',
    cultural: 'Bodo, Khasi, Garo, Manipuri, Mizo & Bhutia folklore stories',
    culturalBn: 'বোড়ো, খাসি, গারো, মণিপুরি, মিজো ও ভুটিয়া লোককথা',
    culturalBrx: 'बड़ो, खासी, गारो, मणिपुरी, मिजो आरो भुटिया लोककथा',
    principle: 'Reminiscence therapy — gentle opinion prompts with no wrong answers',
    glyph: '🏮',
    instructionKey: 'g_tales_intro',
    minDifficulty: 0,
    estimatedMins: 5,
  },
  {
    id: 'garden',
    name: 'Memory Garden (Mindful Orchid Bloom)',
    nameHi: 'स्मृति उद्यान (शांत ध्यान और फूल)',
    nameAs: 'স্মৃতিৰ ফুলনি',
    nameBn: 'স্মৃতির বাগান (অর্কিড ফোটানো)',
    nameBrx: 'गोसोखां बागान (अर्किड)',
    nameMni: 'নিংসিং লেইকোল',
    phase: 3,
    domain: 'Emotional Regulation & Relaxation',
    cultural: 'Caregiver watering and blooming native Himalayan orchids',
    culturalBn: 'পরিচর্যাকারীর জল দেওয়া ও হিমালয়ের অর্কিড ফোটানো',
    culturalBrx: 'मावथाइ थाग्राजों दै होनाय आरो हिमालयनि अर्किड फुदुंनाय',
    principle: 'Mindful breathing & positive reinforcement loop',
    glyph: '🌺',
    instructionKey: 'g_garden_intro',
    minDifficulty: 0,
    estimatedMins: 3,
  },
  {
    id: 'bridge',
    name: 'Number Bridge',
    nameHi: 'संख्या का बांस पुल',
    nameAs: 'সংখ্যাৰ দলং',
    nameBn: 'সংখ্যার বাঁশের সেতু',
    nameBrx: 'बांसनि सेतु आरो नाम्बार',
    nameMni: 'মশিংগী থোং',
    phase: 3,
    domain: 'Serial Number Order',
    cultural: 'Bamboo footbridge across lush paddy fields',
    culturalBn: 'সবুজ ধানক্ষেতের উপর বাঁশের পায়ে চলা সেতু',
    culturalBrx: 'गोब्रा धान खेतनि गेजेराव बांसनि खोनसे सेतु',
    principle: 'Serial sequencing with patient gentle planks',
    glyph: '🌉',
    instructionKey: 'g_bridge_intro',
    minDifficulty: 0,
    estimatedMins: 3,
  },
]

export const gameById = (id: string): GameDef | undefined => GAMES.find((g) => g.id === id)

export function localizedGameName(game: GameDef, lang: Language): string {
  if (lang === 'hi' && game.nameHi) return game.nameHi
  if (lang === 'as' && game.nameAs) return game.nameAs
  if (lang === 'bn' && game.nameBn) return game.nameBn
  if (lang === 'brx' && game.nameBrx) return game.nameBrx
  if (lang === 'mni' && game.nameMni) return game.nameMni
  return game.name
}

export function localizedGameCultural(game: GameDef, lang: Language): string {
  if (lang === 'hi' && game.culturalHi) return game.culturalHi
  if (lang === 'bn' && game.culturalBn) return game.culturalBn
  if (lang === 'brx' && game.culturalBrx) return game.culturalBrx
  return game.cultural
}

export const PHASE_UNLOCK_SESSIONS: Record<Phase, number> = { 1: 0, 2: 4, 3: 8 }

export function unlockedGames(completedSessions: number): GameDef[] {
  return GAMES.filter((g) => completedSessions >= PHASE_UNLOCK_SESSIONS[g.phase])
}
