export type Phase = 1 | 2 | 3

export interface GameDef {
  id: string
  name: string
  nameHi?: string
  nameAs?: string
  nameMni?: string
  phase: Phase
  domain: string
  cultural: string
  principle: string
  glyph: string
  instructionKey: string
  minDifficulty: number
  estimatedMins?: number
}

export const GAMES: GameDef[] = [
  // Phase 1: Familiarization, Episodic & Auditory Recognition
  {
    id: 'faces',
    name: 'Faces of Home',
    nameHi: 'घर के अपने चेहरे',
    nameAs: 'ঘৰৰ চিনাকী মুখবোৰ',
    nameMni: 'ইমুংগী মী',
    phase: 1,
    domain: 'Family & Caregiver Recognition',
    cultural: 'Caregiver photos & regional Northeast family avatars',
    principle: 'Spaced Retrieval Therapy (SRT)',
    glyph: '👪',
    instructionKey: 'g_faces_intro',
    minDifficulty: 0,
    estimatedMins: 3,
  },
  {
    id: 'melodies',
    name: 'Morning Melodies',
    nameHi: 'सुबह की धुनें (पारंपरिक वाद्य)',
    nameAs: 'ৰাতিপুৱাৰ সুৰ',
    nameMni: 'অয়ুক্কী সুর',
    phase: 1,
    domain: 'Auditory & Instrument Recognition',
    cultural: '40+ instruments from Assam, Meghalaya, Manipur, Mizoram, Nagaland, Tripura, Arunachal, Sikkim & India',
    principle: 'Auditory discrimination & errorless cues',
    glyph: '🪘',
    instructionKey: 'g_melodies_intro',
    minDifficulty: 0,
    estimatedMins: 4,
  },
  {
    id: 'objects',
    name: 'Familiar Objects',
    nameHi: 'पहचानी वस्तुएं (घर-आँगन की चीज़ें)',
    nameAs: 'চিনাকী ঘৰুৱা বস্তু',
    nameMni: 'য়ুমগী পোৎলম',
    phase: 1,
    domain: 'Semantic & Object Recognition',
    cultural: 'Tamol cutter, Japi hat, brass handi, clay teapot, tea plucking basket',
    principle: 'Functional & episodic semantic memory',
    glyph: '🧺',
    instructionKey: 'g_objects_intro',
    minDifficulty: 0,
    estimatedMins: 3,
  },
  {
    id: 'tray',
    name: 'Memory Tray',
    nameHi: 'स्मृति थाली (ट्रे की वस्तुएं)',
    nameAs: 'স্মৃতিৰ কাঁহী',
    nameMni: 'নিংসিংশিংগী থালী',
    phase: 1,
    domain: 'Visual Working Memory',
    cultural: 'Kim’s game with morning tea, harvest fruits, flowers & kitchen spices',
    principle: 'Short-term visual retention with gentle reveal',
    glyph: '🍱',
    instructionKey: 'g_tray_intro',
    minDifficulty: 0,
    estimatedMins: 4,
  },
  {
    id: 'sequence',
    name: 'Daily Life Sequence',
    nameHi: 'रोज़मर्रा का क्रम (दिनचर्या)',
    nameAs: 'দৈনন্দিন জীৱনৰ ক্ৰম',
    nameMni: 'নুমিৎ খুদিংগী থবক',
    phase: 1,
    domain: 'Executive Function & Sequencing',
    cultural: 'Morning tea, cooking rice, tamol preparation, harvest & evening prayer',
    principle: 'Errorless learning — slots snap into order',
    glyph: '🫖',
    instructionKey: 'g_sequence_intro',
    minDifficulty: 0,
    estimatedMins: 4,
  },
  {
    id: 'foods',
    name: 'Traditional Foods & Harvest',
    nameHi: 'पारंपरिक खान-पान और फल',
    nameAs: 'পৰম্পৰাগত খাদ্য আৰু ফল',
    nameMni: 'চানবা-থকপগী পোৎ',
    phase: 1,
    domain: 'Semantic Memory & Food Recognition',
    cultural: 'Pitha, Khar, Black rice kheer, Singju, Bai, Momos, Thukpa & mountain citrus',
    principle: 'Reminiscence & cultural recognition',
    glyph: '🍲',
    instructionKey: 'g_foods_intro',
    minDifficulty: 0,
    estimatedMins: 3,
  },
  {
    id: 'pairs',
    name: 'Orchid Pairs',
    nameHi: 'ऑर्किड और फूलों की जोड़ियाँ',
    nameAs: 'ফুলৰ যোৰা মিলাওক',
    nameMni: 'লৈগী যোড়া',
    phase: 1,
    domain: 'Working Memory & Concentration',
    cultural: 'Native Himalayan orchids, lotus & harvest fruits',
    principle: 'Cognitive Stimulation Therapy (CST)',
    glyph: '🪷',
    instructionKey: 'g_pairs_intro',
    minDifficulty: 0,
    estimatedMins: 3,
  },
  {
    id: 'sounds',
    name: 'Village & Nature Sounds',
    nameHi: 'गाँव और प्रकृति की आवाज़ें',
    nameAs: 'গাঁৱৰ আৰু প্ৰকৃতিৰ মাত',
    nameMni: 'খুঙ্গংগী খোঞ্জেল',
    phase: 1,
    domain: 'Auditory Processing & Nature Cues',
    cultural: 'Monsoon rain, mountain river, rooster, cuckoo, evening temple bell, steaming kettle',
    principle: 'Audio-first recognition with zero reading needed',
    glyph: '🔔',
    instructionKey: 'g_sounds_intro',
    minDifficulty: 0,
    estimatedMins: 3,
  },

  // Phase 2: Targeted Cognitive Training, Visual Search, Patterns
  {
    id: 'places',
    name: 'Northeast Places & Nature',
    nameHi: 'पूर्वोत्तर के सुंदर स्थल',
    nameAs: 'উত্তৰ-পূবৰ চিনাকী ঠাই',
    nameMni: 'অৱাং নোংপোক্কী মফমশিং',
    phase: 2,
    domain: 'Visuospatial & Environmental Recognition',
    cultural: 'Living root bridges, Kaziranga, Loktak lake, tea estates, Tawang monastery',
    principle: 'Gentle landmark association & visual orientation',
    glyph: '🏞️',
    instructionKey: 'g_places_intro',
    minDifficulty: 0,
    estimatedMins: 4,
  },
  {
    id: 'loom',
    name: "Weaver's Loom & Motifs",
    nameHi: 'बुनकर की खड़िया और नमूने',
    nameAs: 'তাঁতশালৰ ফুল',
    nameMni: 'য়োংখামগী মচেৎ',
    phase: 2,
    domain: 'Pattern Completion & Visual Attention',
    cultural: 'Gamosa red motifs, Naga shawl bands, Mizo Puan stripes, Manipuri Phanek',
    principle: 'Cognitive pattern recognition & inductive reasoning',
    glyph: '🧶',
    instructionKey: 'g_loom_intro',
    minDifficulty: 0,
    estimatedMins: 4,
  },
  {
    id: 'picture',
    name: 'Picture Memory (Scene Recall)',
    nameHi: 'दृश्य स्मृति (तस्वीर के सवाल)',
    nameAs: 'ছবিৰ স্মৃতি পৰীক্ষা',
    nameMni: 'ফোতো নিংশিংবা',
    phase: 2,
    domain: 'Short-term Visual Observation',
    cultural: 'Bihu courtyard, tea harvest lawn, kitchen veranda, river ferry ghat',
    principle: 'Delayed visual recall & detail attention',
    glyph: '🖼️',
    instructionKey: 'g_picture_intro',
    minDifficulty: 0,
    estimatedMins: 4,
  },
  {
    id: 'bamboo',
    name: 'Category Sorting (Bamboo Baskets)',
    nameHi: 'सही टोकरी में छँटाई (वर्गीकरण)',
    nameAs: 'সাঁচ বাছনি আৰু থাপনা',
    nameMni: 'পোৎলম খায়দোকপা',
    phase: 2,
    domain: 'Categorization & Cognitive Flexibility',
    cultural: 'Sorting fruits, forest animals, tools, handloom textiles & flowers',
    principle: 'Semantic categorization & sorting',
    glyph: '🧺',
    instructionKey: 'g_bamboo_intro',
    minDifficulty: 0,
    estimatedMins: 3,
  },
  {
    id: 'phrases',
    name: 'Familiar Proverbs & Expressions',
    nameHi: 'कहावतें और मीठी बातें',
    nameAs: 'ফকৰা-যোজনা আৰু বাক্য',
    nameMni: 'পাৱারুক অমশুং ৱাখল্লোন',
    phase: 2,
    domain: 'Verbal Association & Reminiscence',
    cultural: 'Hospitality sayings, tea plucking rhymes, farmer proverbs, folk wisdom',
    principle: 'Verbal completion & semantic retrieval',
    glyph: '📜',
    instructionKey: 'g_phrases_intro',
    minDifficulty: 0,
    estimatedMins: 3,
  },
  {
    id: 'safari',
    name: 'Wildlife Safari',
    nameHi: 'वन्यजीव सैर (जंगल के मित्र)',
    nameAs: 'বন্যপ্ৰাণীৰ সন্ধান',
    nameMni: 'উমংগী শাশিং',
    phase: 2,
    domain: 'Visual Search & Concentration',
    cultural: 'One-horned Rhino, Hornbill, Mithun, Asian Elephant, Peacock in Kaziranga',
    principle: 'Figure-ground discrimination in natural scenes',
    glyph: '🦏',
    instructionKey: 'g_safari_intro',
    minDifficulty: 0,
    estimatedMins: 4,
  },
  {
    id: 'cheraw',
    name: 'Cheraw Bamboo Steps',
    nameHi: 'छेराव की ताल (मिज़ो बांस नृत्य)',
    nameAs: 'চেৰাও বাঁহৰ নৃত্য',
    nameMni: 'চেৰাও ডান্স',
    phase: 2,
    domain: 'Rhythmic Attention & Timing',
    cultural: 'Mizo Cheraw rhythmic bamboo dance',
    principle: 'Sustained timing & motor synchronization',
    glyph: '🥢',
    instructionKey: 'g_cheraw_intro',
    minDifficulty: 0,
    estimatedMins: 3,
  },
  {
    id: 'spot',
    name: 'Spot the Difference',
    nameHi: 'फर्क पहचानो (सजग दृष्टि)',
    nameAs: 'পাৰ্থক্য বিচাৰক',
    nameMni: 'খেৎনবা য়েংবা',
    phase: 2,
    domain: 'Selective Visual Attention',
    cultural: 'Tea estate mornings, Bihu courtyard & river landing scenes',
    principle: 'Visual discrimination & focus',
    glyph: '🔍',
    instructionKey: 'g_spot_intro',
    minDifficulty: 0,
    estimatedMins: 3,
  },

  // Phase 3: Reminiscence, Calculation, Emotional Wellbeing
  {
    id: 'market',
    name: 'Market Day (Village Haat)',
    nameHi: 'बाज़ार का दिन (हाट में खरीदारी)',
    nameAs: 'হাঁট-বজাৰৰ দিন',
    nameMni: 'কৈথেল নুমিৎ',
    phase: 3,
    domain: 'Working Memory & Budgeting',
    cultural: 'Friendly local bazaar with fish, honey, seasonal vegetables & wicker baskets',
    principle: 'Anxiety-free everyday calculation & planning',
    glyph: '🛒',
    instructionKey: 'g_market_intro',
    minDifficulty: 0,
    estimatedMins: 4,
  },
  {
    id: 'teawalk',
    name: 'Tea Garden Walk',
    nameHi: 'चाय बागान की सैर',
    nameAs: 'চাহ বাগিচাৰ খোজ',
    nameMni: 'চা পামগী খোঙচৎ',
    phase: 3,
    domain: 'Visuospatial Path Navigation',
    cultural: 'Paved paths through rolling Assam tea hills',
    principle: 'Gentle step tracing & leaf collection',
    glyph: '🍃',
    instructionKey: 'g_teawalk_intro',
    minDifficulty: 0,
    estimatedMins: 3,
  },
  {
    id: 'tales',
    name: 'Festival Tales & Folklore',
    nameHi: 'त्योहारों की सुंदर कहानियाँ',
    nameAs: 'উৎসৱৰ সাধুকথা',
    nameMni: 'ৱারী অমশুং পুৱারী',
    phase: 3,
    domain: 'Verbal Memory & Reminiscence',
    cultural: 'Bodo, Khasi, Garo, Manipuri, Mizo & Bhutia folklore stories',
    principle: 'Reminiscence therapy — gentle opinion prompts with no wrong answers',
    glyph: '🏮',
    instructionKey: 'g_tales_intro',
    minDifficulty: 0,
    estimatedMins: 5,
  },
  {
    id: 'garden',
    name: 'Memory Garden (Mindful Orchid Bloom)',
    nameHi: 'स्मृति उद्यान (शांत ध्यान और फूल)',
    nameAs: 'স্মৃতিৰ ফুলনি',
    nameMni: 'নিংসিং লেইকোল',
    phase: 3,
    domain: 'Emotional Regulation & Relaxation',
    cultural: 'Caregiver watering and blooming native Himalayan orchids',
    principle: 'Mindful breathing & positive reinforcement loop',
    glyph: '🌺',
    instructionKey: 'g_garden_intro',
    minDifficulty: 0,
    estimatedMins: 3,
  },
  {
    id: 'bridge',
    name: 'Number Bridge',
    nameHi: 'संख्या का बांस पुल',
    nameAs: 'সংখ্যাৰ দলং',
    nameMni: 'মশিংগী থোং',
    phase: 3,
    domain: 'Serial Number Order',
    cultural: 'Bamboo footbridge across lush paddy fields',
    principle: 'Serial sequencing with patient gentle planks',
    glyph: '🌉',
    instructionKey: 'g_bridge_intro',
    minDifficulty: 0,
    estimatedMins: 3,
  },
]

export const gameById = (id: string): GameDef | undefined => GAMES.find((g) => g.id === id)

export const PHASE_UNLOCK_SESSIONS: Record<Phase, number> = { 1: 0, 2: 4, 3: 8 }

export function unlockedGames(completedSessions: number): GameDef[] {
  return GAMES.filter((g) => completedSessions >= PHASE_UNLOCK_SESSIONS[g.phase])
}

