p='.sih-build/build.mjs';s=open(p).read()
s=s.replace(" if(box)s.position=box;", " for(const para of paras)for(const r of para)if(typeof r!=='string')s.text.get(r.t).fill='#204D82';\n if(box)s.position=box;")
s=s.replace('Proposed Solution: 23 games with daily memory assistance','Proposed Solution: games and daily memory assistance')
s=s.replace('Recall and attention. ', '23 games. ')
s=s.replace('Orchid Pairs matches hidden cards. Memory Tray recalls a missing item after a 10-second view. [1]','Orchid Pairs matches hidden cards. Memory Tray asks which item disappeared after a 10-second view. [1]')
s=s.replace('Daily Life Sequence orders routines. Traditional Foods recognises regional dishes. Festival Tales invites family conversation. [2, 3]','Order routines in Daily Life Sequence. Recognise regional foods. Share memories through Festival Tales. [2, 3]')
s=s.replace('Six language choices, large controls, offline activities, reminders and a local caregiver view support everyday use.','Six language choices, large controls, offline activities, medicine/routine reminders and a local caregiver view.')
s=s.replace('What is different. ', 'Innovation. ')
s=s.replace('Regional content, gentle cues and difficulty that responds to answers, together in one app.','Regional content and gentle cues combine with difficulty that responds to answers.')
s=s.replace(" [{t:'Optional online services. '},'A server proxy connects chat and speech providers. Core play continues offline.'],\n [{t:'Next engineering step. '},'Connect question ranking to real answer timing and hint events.']", " [{t:'Optional online services. '},'A server proxy connects chat and speech providers. Core play continues offline.']")
s=s.replace('The current prototype combines games, local adaptation, reminders and a caregiver view on standard mobile/tablet hardware.','Games, local adaptation, reminders and caregiver views run on standard mobile/tablet hardware.')
s=s.replace('Speech coverage varies by language. Notifications depend on device permissions. Local records can disappear if app data is cleared.','Speech support varies by language. Notifications need permissions. Clearing app data can erase local records.')
s=s.replace('Use cached audio and text fallbacks. Check notification permissions. Add encrypted backup, authentication and multi-device sync before wider deployment.','Use cached audio and text fallbacks. Check permissions. Add encrypted backup, authentication and sync before wider deployment.')
s=s.replace('Review regional content with native speakers, test accessibility with older adults, and run a clinician-supervised pilot.','Native-speaker review, accessibility sessions with older adults, then a clinician-supervised pilot.')
s=s.replace('Familiar activities and gentle prompts aim to make daily engagement easier and encourage shared play with family.','Familiar activities aim to encourage daily engagement and shared play with family.')
s=s.replace('One local view brings together completed sessions, reminder logs and activity trends for follow-up conversations.','One local view shows completed sessions, reminder logs and activity trends.')
s=s.replace('Core use needs no continuous connection or dedicated hardware. Optional cloud services add running costs.','Core use needs no continuous connection or special hardware. Optional cloud services add running costs.')
s=s.replace('Track session completion, reminder acknowledgement, caregiver effort and usability in a pilot. Clinical benefit remains unproven.','Measure completion, reminder acknowledgement, caregiver effort and usability in a pilot. Clinical benefit remains unproven.')
s=s.replace('Computerised memory training: Orchid Pairs and Memory Tray. Dementia evidence is limited.','Memory training. Design link: Pairs and Tray. Dementia evidence is limited.')
s=s.replace('Cognitive stimulation: varied recall, word and routine activities. Mostly group-based evidence.','Cognitive stimulation. Design link: varied activities. Evidence is mostly from groups.')
s=s.replace('Online Life Story Book trial: family memories and Festival Tales. Most outcomes were not significant.','Life Story Book trial. Design link: Festival Tales. Most outcomes were not significant.')
s=s.replace('Papers published within the last five years. These studies do not validate Smriti Sathi.','2021–2026 research. These papers do not validate Smriti Sathi.')
# Preserve the terminology of the template while filling the content.
s=s.replace("notes[4] +=", "notes[1] += '\\nAdditional code detail: Picture Memory records difficulty updates, but its content generator currently ignores the level argument. Faces of Home uses a fixed five-round sequence. Do not claim every game changes its content difficulty after every answer.';\nnotes[4] +=")
open(p,'w').write(s)
