export interface FamiliarObjectItem {
  id: string
  name: string
  nameHi: string
  nameAs?: string
  nameMni?: string
  emoji: string
  category: 'kitchen' | 'craft' | 'daily' | 'farming' | 'attire' | 'ceremony'
  cueQuestion: string
  cueQuestionHi: string
  cueQuestionAs?: string
  culturalNote: string
  distractorCategory: string
}

export const FAMILIAR_OBJECTS_BANK: FamiliarObjectItem[] = [
  {
    id: 'tamol_cutter',
    name: 'Tamol Cutter (Sarota)',
    nameHi: 'सरोता (तामोल कटर)',
    nameAs: 'জাতি / তামোল কটাৰী',
    nameMni: 'খুৰচাং',
    emoji: '✂️',
    category: 'daily',
    cueQuestion: 'Which one is used to cut betel nut (Tamol)?',
    cueQuestionHi: 'सुपारी (तामोल) काटने के लिए कौन सा औज़ार इस्तेमाल होता है?',
    culturalNote: 'Traditional brass or iron nut-cracker found in every Assamese & Northeast household.',
    distractorCategory: 'tools',
  },
  {
    id: 'japi_hat',
    name: 'Japi (Bamboo Conical Hat)',
    nameHi: 'जापी (बांस की टोपी)',
    nameAs: 'জাপি',
    nameMni: 'জাপি',
    emoji: '👒',
    category: 'attire',
    cueQuestion: 'Which one is worn on the head to shield from rain and sun in the fields?',
    cueQuestionHi: 'खेतों में धूप और बारिश से बचने के लिए सिर पर क्या पहना जाता है?',
    culturalNote: 'Woven bamboo and palm-leaf conical headgear, symbol of Assamese welcome and dignity.',
    distractorCategory: 'clothing',
  },
  {
    id: 'brass_handi',
    name: 'Brass Cooking Handi / Degchi',
    nameHi: 'पीतल की हांड़ी / देगची',
    nameAs: 'কাঁহৰ চৰু',
    nameMni: 'য়োৎপু',
    emoji: '🍲',
    category: 'kitchen',
    cueQuestion: 'Which one is used for cooking rice and warm meals on the stove?',
    cueQuestionHi: 'चूल्हे पर भात और खाना पकाने के लिए क्या इस्तेमाल होता है?',
    culturalNote: 'Traditional heavy-bottom brass and bell-metal pot used for slow-cooking aromatic rice.',
    distractorCategory: 'kitchenware',
  },
  {
    id: 'gamosa',
    name: 'Gamosa (Red & White Woven Towel)',
    nameHi: 'गमोसा (पारंपरिक वस्त्र)',
    nameAs: 'গামোচা',
    nameMni: 'ꯈꯨꯗꯩ (Khudei)',
    emoji: '🧣',
    category: 'attire',
    cueQuestion: 'Which one is the red-and-white woven cotton scarf given as a sign of deep respect?',
    cueQuestionHi: 'सम्मान और आदर के प्रतीक के रूप में कौन सा लाल-सफेद बुना वस्त्र दिया जाता है?',
    culturalNote: 'Sacred handwoven Assamese textile with red floral Phulam borders.',
    distractorCategory: 'textiles',
  },
  {
    id: 'tea_basket',
    name: 'Wicker Tea Basket (Tukuri)',
    nameHi: 'चाय की टोकरी (टुकुरी)',
    nameAs: 'টুকোৰী / খৰাহী',
    nameMni: 'পৈৰেং',
    emoji: '🧺',
    category: 'farming',
    cueQuestion: 'Which one is carried on the back to collect freshly plucked tender tea leaves?',
    cueQuestionHi: 'ताज़ी चाय की पत्तियाँ चुनकर पीठ पर किसमें रखी जाती हैं?',
    culturalNote: 'Lightweight bamboo wicker basket strapped around the head with a band.',
    distractorCategory: 'containers',
  },
  {
    id: 'clay_teapot',
    name: 'Clay Kettle / Teapot',
    nameHi: 'मिट्टी की केतली / चायदानी',
    nameAs: 'চাহৰ কেটলি',
    nameMni: 'চা পূং',
    emoji: '🫖',
    category: 'kitchen',
    cueQuestion: 'Which one is used to boil and pour warm morning tea?',
    cueQuestionHi: 'सुबह की गर्मागर्म चाय उबालने और परोसने के लिए क्या इस्तेमाल होता है?',
    culturalNote: 'Essential morning companion in every home across Assam and Northeast hills.',
    distractorCategory: 'drinkware',
  },
  {
    id: 'loom_shuttle',
    name: 'Loom Shuttle (Maku / Tat Xal)',
    nameHi: 'हथकरघे की फिरकी (माकू)',
    nameAs: 'মাকো',
    nameMni: 'ꯅꯥꯆꯣꯝ (Loom shuttle)',
    emoji: '🧵',
    category: 'craft',
    cueQuestion: 'Which one carries the thread back and forth while weaving on the handloom?',
    cueQuestionHi: 'हथकरघे पर कपड़ा बुनते समय धागे को इधर-उधर कौन ले जाता है?',
    culturalNote: 'Smooth wooden boat-shaped shuttle used in handloom weaving across Northeast villages.',
    distractorCategory: 'craft_tools',
  },
  {
    id: 'mortar_pestle',
    name: 'Wooden Mortar & Pestle (Uron / Ural)',
    nameHi: 'ओखली और मूसल',
    nameAs: 'উৰাল-মৰী',
    nameMni: 'ꯁꯨꯝꯕꯥꯜ',
    emoji: '🥣',
    category: 'kitchen',
    cueQuestion: 'Which one is used to pound rice flour and crush aromatic spices by hand?',
    cueQuestionHi: 'चावल का आटा कूटने और मसालों को पीसने के लिए क्या उपयोग किया जाता है?',
    culturalNote: 'Heavy carved timber mortar used for making fine pitha rice powder and traditional pastes.',
    distractorCategory: 'kitchen_tools',
  },
  {
    id: 'bamboo_mora',
    name: 'Bamboo Cane Stool (Mora)',
    nameHi: 'बांस का मोढ़ा (बैठने का स्टूल)',
    nameAs: 'মূঢ়া',
    nameMni: 'মৌৰা',
    emoji: '🪑',
    category: 'daily',
    cueQuestion: 'Which one is the woven cane stool for sitting comfortably in the veranda?',
    cueQuestionHi: 'बरामदे में आराम से बैठने के लिए बांस और बेंत का कौन सा स्टूल रखा होता है?',
    culturalNote: 'Lightweight, durable round stool crafted from bamboo reeds and cane strips.',
    distractorCategory: 'furniture',
  },
  {
    id: 'earthen_pitcher',
    name: 'Clay Water Pitcher (Koloh)',
    nameHi: 'मिट्टी का घड़ा / कलश',
    nameAs: 'মাটিৰ কলহ',
    nameMni: 'ꯄꯨꯟ (Clay pot)',
    emoji: '🏺',
    category: 'kitchen',
    cueQuestion: 'Which one keeps drinking water naturally cool during warm summer days?',
    cueQuestionHi: 'गर्मियों में पीने के पानी को प्राकृतिक रूप से ठंडा रखने के लिए क्या इस्तेमाल होता है?',
    culturalNote: 'Porous terracotta water jar placed in the kitchen corner to keep water sweet and cool.',
    distractorCategory: 'pottery',
  },
  {
    id: 'fishing_polo',
    name: 'Bamboo Fishing Trap (Polo / Sepa)',
    nameHi: 'बांस की मछली पकड़ने वाली जाली (पोलो)',
    nameAs: 'পলো / চেপা',
    nameMni: 'ꯂꯨ (Bamboo fish trap)',
    emoji: '🕸️',
    category: 'farming',
    cueQuestion: 'Which bamboo woven trap is plunged into shallow river water to catch fresh fish?',
    cueQuestionHi: 'उथले पानी और नदी में मछली पकड़ने के लिए बांस का कौन सा ढांचा डुबोया जाता है?',
    culturalNote: 'Bell-shaped bamboo basket trap plunged into river mud during community fishing.',
    distractorCategory: 'fishing',
  },
  {
    id: 'evening_diya',
    name: 'Clay Oil Lamp (Chaki / Diya)',
    nameHi: 'मिट्टी का दीपक (दीया / साकी)',
    nameAs: 'মাটিৰ চাকি',
    nameMni: 'ꯊꯥꯎꯃꯩ',
    emoji: '🪔',
    category: 'ceremony',
    cueQuestion: 'Which one is filled with mustard oil and lit under the Tulsi plant at twilight?',
    cueQuestionHi: 'संध्या समय तुलसी के पौधे के नीचे सरसों के तेल से क्या जलाया जाता है?',
    culturalNote: 'Small earthen lamp lit in home courtyards to bring peace, warmth, and blessings.',
    distractorCategory: 'lamps',
  },
  {
    id: 'grinding_stone',
    name: 'Stone Sil-Pata (Grinding Slab)',
    nameHi: 'सिल-बट्टा (मसाला पत्थर)',
    nameAs: 'পটা-গুটি',
    nameMni: 'ꯅꯨꯡ (Grinding stone)',
    emoji: '🪨',
    category: 'kitchen',
    cueQuestion: 'Which stone slab is used to grind fresh mint, garlic, and ginger paste?',
    cueQuestionHi: 'अदरक, लहसुन और ताज़ा धनिया पीसने के लिए किस पत्थर की पट्टी का उपयोग होता है?',
    culturalNote: 'Flat granite slab and roller stone essential to traditional culinary preparations.',
    distractorCategory: 'grinders',
  },
  {
    id: 'bamboo_sieve',
    name: 'Bamboo Winnowing Sieve (Dala / Kula)',
    nameHi: 'सूप / चालनी (डला)',
    nameAs: 'ডলা / কুলা',
    nameMni: 'ꯌꯥꯡꯀꯣꯛ',
    emoji: '🧹',
    category: 'farming',
    cueQuestion: 'Which flat woven tray is tossed gently in the breeze to clean paddy grains?',
    cueQuestionHi: 'हवा में उछालकर धान और अनाज से भूसी अलग करने के लिए क्या इस्तेमाल होता है?',
    culturalNote: 'Heart of grain processing in every agricultural village.',
    distractorCategory: 'sieves',
  },
  {
    id: 'bell_metal_thali',
    name: 'Bell-Metal Dining Platter (Kahi-Bati)',
    nameHi: 'कांस्य धातु की थाली (काही-बाटी)',
    nameAs: 'কাঁহৰ কাঁহী-বাটি',
    nameMni: 'ꯄꯨꯛꯈꯝ',
    emoji: '🍽️',
    category: 'kitchen',
    cueQuestion: 'Which heavy golden metal platter is used to serve festive meals with dignity?',
    cueQuestionHi: 'सार्टोरियल और पारंपरिक भोजन परोसने के लिए कांसे की कौन सी थाली उपयोग होती है?',
    culturalNote: 'Handmade bell-metal dining set from Sarthebari, famous for health benefits and sheen.',
    distractorCategory: 'tableware',
  },
  {
    id: 'handloom_bobbin',
    name: 'Wooden Bobbin (Sereki / Bobbin)',
    nameHi: 'चरखी / सूत की लच्छी',
    nameAs: 'চেৰেকী',
    nameMni: 'ꯇꯔꯦꯡ',
    emoji: '🧶',
    category: 'craft',
    cueQuestion: 'Which revolving wooden frame winds raw silk yarn smoothly onto spools?',
    cueQuestionHi: 'रेशम के कच्चे धागे को लपेटने के लिए घूमने वाली लकड़ी की चरखी कौन सी है?',
    culturalNote: 'Traditional spinning accessory found beside handlooms in Sualkuchi and rural homes.',
    distractorCategory: 'crafts',
  },
  {
    id: 'paddy_sickle',
    name: 'Harvest Sickle (Kachi)',
    nameHi: 'हँसिया (दांती)',
    nameAs: 'কাঁচি',
    nameMni: 'ꯊꯥꯡꯒꯣꯜ',
    emoji: '🌾',
    category: 'farming',
    cueQuestion: 'Which curved metal blade is used to harvest golden winter paddy stalks?',
    cueQuestionHi: 'पके हुए सुनहरे धान के पौधों को काटने के लिए कौन सा औज़ार काम आता है?',
    culturalNote: 'Curved agricultural tool used during Magh Bihu harvest season.',
    distractorCategory: 'tools',
  },
  {
    id: 'bamboo_umbrella',
    name: 'Traditional Umbrella (Japi Chati)',
    nameHi: 'बांस का बड़ा छाता',
    nameAs: 'ছতি / ছাতি',
    nameMni: 'ꯆꯠꯔ',
    emoji: '☂️',
    category: 'daily',
    cueQuestion: 'Which handy companion keeps off the heavy monsoon downpours on a walk?',
    cueQuestionHi: 'बरसात में पैदल चलते समय भारी बारिश से बचने के लिए क्या खोला जाता है?',
    culturalNote: 'Essential protection against Northeast monsoon rain.',
    distractorCategory: 'rain_gear',
  },
  {
    id: 'betel_box',
    name: 'Bata / Paan Container',
    nameHi: 'पीतल का पानदान (बटा)',
    nameAs: 'কাঁহৰ বঁটা',
    nameMni: 'ꯀ꯭ꯕꯥ ꯊꯥꯛ',
    emoji: '🍱',
    category: 'ceremony',
    cueQuestion: 'Which elevated brass stand is used to offer betel nuts and Paan to respected guests?',
    cueQuestionHi: 'आए हुए अतिथियों को आदरपूर्वक पान और सुपारी भेंट करने वाला सुंदर पीतल का पात्र कौन सा है?',
    culturalNote: 'Raised pedestal tray of bell-metal, central to Assamese etiquette and hospitality.',
    distractorCategory: 'ceremonial',
  },
  {
    id: 'iron_tawa',
    name: 'Heavy Iron Roti Tawa',
    nameHi: 'लोहे का तवा',
    nameAs: 'লোৰ তাৱা',
    nameMni: 'ꯇꯋꯥ',
    emoji: '🍳',
    category: 'kitchen',
    cueQuestion: 'Which flat circular pan is used to bake hot rotis and crisp dosas over fire?',
    cueQuestionHi: 'गर्मागर्म रोटियाँ और पराठे सेकने के लिए किस गोल तवे का इस्तेमाल होता है?',
    culturalNote: 'Durable cast iron skillet seasoned over decades in home kitchens.',
    distractorCategory: 'pans',
  },
  {
    id: 'clay_curd_pot',
    name: 'Earthen Curd Pot (Doi Khura)',
    nameHi: 'दही का मिट्टी का सकोरा / कुल्हड़',
    nameAs: 'দৈৰ খুৰা',
    nameMni: 'ꯗꯍꯤ ꯄꯨꯟ',
    emoji: '🥛',
    category: 'kitchen',
    cueQuestion: 'Which earthen bowl sets sweet creamy curd and yogurt naturally thick?',
    cueQuestionHi: 'गाढ़ा और मीठा दही जमाने के लिए कौन सा मिट्टी का बर्तन इस्तेमाल होता है?',
    culturalNote: 'Red clay vessel that absorbs excess moisture to make thick Jolpan curd.',
    distractorCategory: 'curd_pots',
  },
  {
    id: 'bamboo_steamer',
    name: 'Bamboo Pitha Steamer (Sunga / Tekeli)',
    nameHi: 'बांस का स्टीमर (सुंगा / भाप बर्तन)',
    nameAs: 'চুঙা / টেকেলী মুখ',
    nameMni: 'ꯆꯥꯛ ꯊꯣꯡꯕꯥ ꯋꯥ',
    emoji: '♨️',
    category: 'kitchen',
    cueQuestion: 'Which hollow bamboo tube is packed with sticky rice and roasted over firewood?',
    cueQuestionHi: 'बांस की खोखली नली में चावल भरकर आग पर क्या पकाया जाता है (सुंगा चावल)?',
    culturalNote: 'Green bamboo segment used for traditional aromatic Sunga Saul & Pitha preparation.',
    distractorCategory: 'steamers',
  },
  {
    id: 'wool_shawl',
    name: 'Naga / Mizo Woven Shawl',
    nameHi: 'गर्म ऊनी शॉल (नागा / मिज़ो पुआन)',
    nameAs: 'উমাল শাল',
    nameMni: 'ꯏꯟꯅꯥꯐꯤ',
    emoji: '🧣',
    category: 'attire',
    cueQuestion: 'Which warm woven wrap is draped over shoulders on chilly winter mornings?',
    cueQuestionHi: 'सर्दियों की सुबह ठंड से बचने के लिए कंधों पर क्या ओढ़ा जाता है?',
    culturalNote: 'Thick handwoven wool wrap decorated with tribal geometric color bands.',
    distractorCategory: 'winterwear',
  },
  {
    id: 'wooden_walking_stick',
    name: 'Carved Cane Walking Stick',
    nameHi: 'बेंत की लाठी / छड़ी',
    nameAs: 'বেতৰ লাখুটি',
    nameMni: 'ꯆꯩ',
    emoji: '🦯',
    category: 'daily',
    cueQuestion: 'Which smooth cane stick offers steady support and balance while walking in the garden?',
    cueQuestionHi: 'बगीचे में टहलते समय संतुलन और सहारे के लिए क्या हाथ में लिया जाता है?',
    culturalNote: 'Natural hill cane walking staff hand-polished by local artisans.',
    distractorCategory: 'mobility',
  },
  {
    id: 'prayer_beads',
    name: 'Tulsi / Rudraksha Mala (Prayer Beads)',
    nameHi: 'तुलसी / रुद्राक्ष की जप माला',
    nameAs: 'জপ মালা',
    nameMni: 'ꯖꯞ ꯃꯥꯂꯥ',
    emoji: '📿',
    category: 'ceremony',
    cueQuestion: 'Which string of wooden beads is held gently in hand for morning meditation and prayer?',
    cueQuestionHi: 'सुबह शांत बैठकर प्रभु स्मरण और जप करने के लिए क्या हाथ में लिया जाता है?',
    culturalNote: 'Sacred beads turned one by one for inner calm and focus.',
    distractorCategory: 'beads',
  },
  {
    id: 'flower_basket',
    name: 'Small Puja Flower Basket (Saji)',
    nameHi: 'फूलों की छोटी डलिया (साजी)',
    nameAs: 'ফুলৰ সাজি',
    nameMni: 'লৈ ꯄꯨꯛ',
    emoji: '🧺',
    category: 'daily',
    cueQuestion: 'Which little wicker basket is carried to pick fresh hibiscus and jasmine flowers at dawn?',
    cueQuestionHi: 'सुबह-सुबह बगिया से ताज़ा चमेली और गुड़हल के फूल चुनने के लिए क्या ले जाते हैं?',
    culturalNote: 'Delicate mini bamboo basket kept in the prayer room.',
    distractorCategory: 'mini_baskets',
  },
  {
    id: 'bamboo_rake',
    name: 'Garden Bamboo Rake',
    nameHi: 'बांस का पंजा (पत्तियां बटोरने वाला)',
    nameAs: 'পাত সৰা জেং',
    nameMni: 'ꯀꯪꯁꯨ',
    emoji: '🧹',
    category: 'farming',
    cueQuestion: 'Which bamboo tool gathers fallen autumn leaves from the courtyard grass?',
    cueQuestionHi: 'आंगन से सूखी पत्तियां एक जगह बटोरने के लिए कौन सा बांस का पंजा काम आता है?',
    culturalNote: 'Flexible bamboo tool for keeping courtyard grounds tidy.',
    distractorCategory: 'garden_tools',
  },
  {
    id: 'clay_incense_holder',
    name: 'Clay Dhuna Incense Burner (Dhuna Dani)',
    nameHi: 'धूपदानी (धुना दानी)',
    nameAs: 'ধূনা দানি',
    nameMni: 'ꯙꯨꯞ ꯄꯨꯡ',
    emoji: '🕯️',
    category: 'ceremony',
    cueQuestion: 'Which terracotta vessel burns fragrant coconut husk and resin in the evening?',
    cueQuestionHi: 'शाम को सुगंधित धूप और लोबान सुलगाने के लिए कौन सी मिट्टी की धूपदानी इस्तेमाल होती है?',
    culturalNote: 'Clay vessel that purifies home air and repels evening insects with natural tree resin.',
    distractorCategory: 'burners',
  },
  {
    id: 'hand_fan',
    name: 'Woven Palm-Leaf Hand Fan (Bichoni)',
    nameHi: 'हाथ का पंखा (बिचोनी)',
    nameAs: 'বিচনী',
    nameMni: 'ꯍꯨꯝꯃꯥꯏ',
    emoji: '🪭',
    category: 'daily',
    cueQuestion: 'Which woven hand fan provides a gentle cool breeze on a quiet afternoon?',
    cueQuestionHi: 'दोपहर की गर्मी में ठंडी और सुखद हवा देने के लिए कौन सा हाथ का पंखा काम आता है?',
    culturalNote: 'Cane or palm leaf fan embroidered with cotton thread patterns.',
    distractorCategory: 'fans',
  },
  {
    id: 'seed_storage_pot',
    name: 'Grain Storage Bamboo Basket (Duli / Bharal)',
    nameHi: 'अनाज की बड़ी कोठी (डूली / भंड़ार)',
    nameAs: 'ডুলি / ধানৰ ভঁৰাল',
    nameMni: 'ꯀꯣꯠ',
    emoji: '🌾',
    category: 'farming',
    cueQuestion: 'Which large woven cylinder stores harvested golden paddy safe from moisture?',
    cueQuestionHi: 'साल भर के लिए धान और अनाज सुरक्षित रखने वाली बांस की बड़ी कोठी कौन सी है?',
    culturalNote: 'Plastered bamboo grain storage bin in village storehouses.',
    distractorCategory: 'granaries',
  },
  {
    id: 'kula_winnow',
    name: 'Woven Winnowing Tray (Kula / Sup)',
    nameHi: 'सूप / सूपड़ा (कुला)',
    nameAs: 'কুলা',
    nameMni: 'ꯌꯥꯡꯀꯣꯛ',
    emoji: '🪵',
    category: 'farming',
    cueQuestion: 'Which flat bamboo tray is shaken in the wind to separate grain from chaff?',
    cueQuestionHi: 'धान और अनाज से भूसा अलग करने के लिए कौन सा सूप फटका जाता है?',
    culturalNote: 'Essential kitchen & harvest winnowing tray.',
    distractorCategory: 'trays',
  },
  {
    id: 'kolakhar_filter',
    name: 'Kolakhar Bamboo Filter (Khar Khoroni)',
    nameHi: 'कोलाखार की छलनी (केले की राख का अर्क)',
    nameAs: 'খাৰ খোৰণি',
    nameMni: 'ꯎꯇꯣꯡ',
    emoji: '🎋',
    category: 'kitchen',
    cueQuestion: 'Which bamboo funnel filters clear alkaline water through banana ash for cooking Khar?',
    cueQuestionHi: 'असमिया व्यंजन खार बनाने के लिए केले की राख छानने वाला बांस का कीप कौन सा है?',
    culturalNote: 'Traditional indigenous alkaline water filtration cone.',
    distractorCategory: 'filters',
  },
  {
    id: 'pitha_mould',
    name: 'Wooden Pitha Mould (Pitha Sanchi)',
    nameHi: 'पीठा बनाने का लकड़ी का सांचा',
    nameAs: 'পিঠাৰ সাঁচ',
    nameMni: 'ꯆꯦꯡ ꯃꯥꯎꯜꯗ',
    emoji: '🧇',
    category: 'kitchen',
    cueQuestion: 'Which carved wooden stamp presses beautiful flower patterns onto festive rice pithas?',
    cueQuestionHi: 'बिहू के पीठे पर सुंदर फूल की नक्काशी छापने वाला लकड़ी का सांचा कौन सा है?',
    culturalNote: 'Artisan carved wood stamp for festive rice treats.',
    distractorCategory: 'moulds',
  },
  {
    id: 'fish_polo_trap',
    name: 'Conical Bamboo Fish Trap (Polo)',
    nameHi: 'पोलो (बांस का मछली पकड़ने का पिंजरा)',
    nameAs: 'প’ল’',
    nameMni: 'ꯂꯨꯞ',
    emoji: '🧺',
    category: 'farming',
    cueQuestion: 'Which conical bamboo basket is plunged into shallow river water to trap fresh fish?',
    cueQuestionHi: 'नदी या पोखर के उथले पानी में दबाकर मछली पकड़ने वाला बांस का पोलो कौन सा है?',
    culturalNote: 'Traditional community fishing trap used during festive river fishing.',
    distractorCategory: 'traps',
  },
  {
    id: 'bamboo_tea_cup',
    name: 'Carved Bamboo Tea Cup (Banh Bati)',
    nameHi: 'बांस का चाय का प्याला',
    nameAs: 'বাঁহৰ বাটি',
    nameMni: 'ꯎꯇꯣꯡ ꯀꯞ',
    emoji: '🍵',
    category: 'kitchen',
    cueQuestion: 'Which polished bamboo cup is used to sip warm herbal tea in the hills?',
    cueQuestionHi: 'पहाड़ों में गर्म लाल चाय या काढ़ा पीने के लिए कौन सा बांस का प्याला इस्तेमाल होता है?',
    culturalNote: 'Naturally insulated green bamboo drinkware.',
    distractorCategory: 'cups',
  },
  {
    id: 'curd_earthen_pot',
    name: 'Earthen Curd Pot (Doi Mala)',
    nameHi: 'मिट्टी की दही की मटकी (दोई माला)',
    nameAs: 'দৈৰ মালা',
    nameMni: 'ꯙꯥꯏ ꯄꯨꯡ',
    emoji: '🏺',
    category: 'kitchen',
    cueQuestion: 'Which cool terracotta bowl sets thick creamy village curd with jaggery?',
    cueQuestionHi: 'गुड़ और चूड़ा के साथ गाढ़ी मलाईदार दही जमाने वाली मिट्टी की मटकी कौन सी है?',
    culturalNote: 'Porous clay pot that sets naturally chilled sweet curd.',
    distractorCategory: 'curd_pots',
  },
  {
    id: 'iron_tongs',
    name: 'Hearth Iron Tongs (Chimta / Xonrashi)',
    nameHi: 'अंगीठी का चिमटा',
    nameAs: 'সোণৰাশী',
    nameMni: 'ꯌꯣꯠ ꯆꯤꯝꯇꯥ',
    emoji: '🥢',
    category: 'kitchen',
    cueQuestion: 'Which iron tool safely adjusts glowing wood embers in the kitchen hearth?',
    cueQuestionHi: 'रसोई के चूल्हे में जलती हुई लकड़ियों को पलटने के लिए कौन सा चिमटा काम आता है?',
    culturalNote: 'Sturdy black iron blacksmith tongs for wood stoves.',
    distractorCategory: 'tongs',
  },
]

export const getFamiliarObjectById = (id: string): FamiliarObjectItem | undefined =>
  FAMILIAR_OBJECTS_BANK.find((o) => o.id === id)
