export type InstrumentId =
  // Assam
  | 'dhol'
  | 'pepa'
  | 'flute'
  | 'tokari'
  | 'gagana'
  | 'gogona'
  | 'khol'
  | 'bhor_taal'
  // Meghalaya (Khasi / Garo / Jaintia)
  | 'wangala'
  | 'tangmuri'
  | 'singphong'
  | 'dama'
  | 'maryngod'
  // Manipur
  | 'pena'
  | 'pung'
  | 'khartal'
  | 'maram_drum'
  // Mizoram
  | 'khuang'
  | 'rawchhem'
  | 'darphym'
  | 'darphym_gong'
  // Nagaland
  | 'log_drum'
  | 'tati'
  | 'petu'
  // Tripura
  | 'sarinda'
  | 'kham'
  | 'sumui'
  | 'chongpreng'
  // Arunachal Pradesh
  | 'ponung'
  | 'jachin'
  | 'dranyen'
  | 'chime_gong'
  // Sikkim
  | 'gyaling'
  | 'damphu'
  | 'tungna'
  | 'suthe'
  // Classic Indian
  | 'tabla'
  | 'harmonium'
  | 'sitar'
  | 'shehnai'
  | 'dholak'
  | 'ektara'
  | 'manjira'
  | 'bell'

export interface InstrumentItem {
  id: InstrumentId
  name: string
  nameHi?: string
  nameAs?: string
  nameMni?: string
  region: string
  state: string
  emoji: string
  description: string
  descriptionHi?: string
  soundPreset: InstrumentId
  family: 'percussion' | 'wind' | 'string' | 'idiophone'
}

export const INSTRUMENT_BANK: InstrumentItem[] = [
  // ASSAM
  {
    id: 'dhol',
    name: 'Bihu Dhol',
    nameHi: 'बीहू ढोल',
    nameAs: 'বিহু ঢোল',
    nameMni: 'বিহু ঢোল',
    region: 'Brahmaputra Valley',
    state: 'Assam',
    emoji: '🪘',
    description: 'Double-headed barrel drum played with a bamboo stick during Rongali Bihu.',
    descriptionHi: 'रोंगाली बीहू में बजाया जाने वाला पारंपरिक लकड़ी का ढोल।',
    soundPreset: 'dhol',
    family: 'percussion',
  },
  {
    id: 'suthe',
    name: 'Suthe / Tungbuk Horn',
    nameHi: 'सुथे / तुंगबुक सींग',
    nameAs: 'সুথে শিঙা',
    nameMni: 'সুথে',
    state: 'Sikkim',
    region: 'Himalayan wind',
    emoji: '📯',
    soundPreset: 'gyaling',
    family: 'wind',
    description: 'Traditional Lepcha mountain curved horn sounding over snow ranges',
    descriptionHi: 'लेप्चा पर्वत शृंग',
  },
  {
    id: 'gogona',
    name: 'Gogona (Bamboo Jaw Harp)',
    nameHi: 'गगना (बांस की चंग)',
    nameAs: 'গগনা',
    nameMni: 'গগনা',
    state: 'Assam',
    region: 'Bihu vibrating reed',
    emoji: '🎋',
    soundPreset: 'gagana',
    family: 'idiophone',
    description: 'Slender bamboo reed instrument held in the teeth and vibrated with the fingers in Rongali Bihu',
    descriptionHi: 'रोंगाली बिहू में दांतों से बजाया जाने वाला बांस का वाद्य',
  },
  {
    id: 'chime_gong',
    name: 'Monastery Bronze Gong',
    nameHi: 'मठ का कांस्य घंटा',
    nameAs: 'মঠৰ ব্ৰঞ্জ ঘণ্টা',
    nameMni: 'মঠকী বেল',
    state: 'Arunachal Pradesh',
    region: 'Buddhist prayer chime',
    emoji: '🔔',
    soundPreset: 'bell',
    family: 'idiophone',
    description: 'Deep resonating bronze prayer gong sounded at morning monastery chanting in Tawang',
    descriptionHi: 'तवांग मठ में सुबह की प्रार्थना में बजने वाला कांस्य घंटा',
  },
  {
    id: 'maram_drum',
    name: 'Maram Log Drum',
    nameHi: 'मराम काठ ढोल',
    nameAs: 'মৰাম কাঠৰ ঢোল',
    nameMni: 'মরাম পুং',
    state: 'Manipur',
    region: 'Hill community percussion',
    emoji: '🪵',
    soundPreset: 'log_drum',
    family: 'percussion',
    description: 'Carved giant wooden log drum resonated for harvest celebrations',
    descriptionHi: 'फसल उत्सवों में बजाया जाने वाला विशाल काठ ढोल',
  },
  {
    id: 'darphym_gong',
    name: 'Darphym Brass Bell',
    nameHi: 'दरफिम पीतल घंटी',
    nameAs: 'দৰফিম কাঁহৰ ঘণ্টা',
    nameMni: 'দরফিম বেল',
    state: 'Mizoram',
    region: 'Ceremonial gong chime',
    emoji: '🔔',
    soundPreset: 'bell',
    family: 'idiophone',
    description: 'Clear brass gong struck during harvest festivals in Mizoram',
    descriptionHi: 'मिज़ोरम के चापचार कुट उत्सव में बजने वाला पीतल का घंटा',
  },

  {
    id: 'pepa',
    name: 'Pepa Horn',
    nameHi: 'पेपा बाजा',
    nameAs: 'পেঁপা',
    nameMni: 'পেপা',
    region: 'Assam Plains',
    state: 'Assam',
    emoji: '📯',
    description: 'Traditional hornpipe made from buffalo horn and bamboo reed.',
    descriptionHi: 'भैंस के सींग और बांस की नली से बना पारंपरिक लोक वाद्य।',
    soundPreset: 'pepa',
    family: 'wind',
  },
  {
    id: 'flute',
    name: 'Bahi (Bamboo Flute)',
    nameHi: 'बांसुरी (बाही)',
    nameAs: 'বাঁহী',
    nameMni: 'ৱাংগোং',
    region: 'Northeast Hills & Plains',
    state: 'Assam',
    emoji: '🪈',
    description: 'Melodious side-blown bamboo flute played across Assam and Northeast folk traditions.',
    descriptionHi: 'बांस से बनी सुरीली बांसुरी, जो लोक धुनों में गूंजती है।',
    soundPreset: 'flute',
    family: 'wind',
  },
  {
    id: 'tokari',
    name: 'Tokari',
    nameHi: 'तोकारी',
    nameAs: 'টোকোৰী',
    nameMni: 'তোকারী',
    region: 'Upper Assam',
    state: 'Assam',
    emoji: '🪕',
    description: 'Ancient plucked string instrument used by folk bards for devotional Tokari Geet.',
    descriptionHi: 'असम का प्राचीन तार वाद्य, जो भक्ति गीतों में बजाया जाता है।',
    soundPreset: 'tokari',
    family: 'string',
  },
  {
    id: 'gagana',
    name: 'Gagana (Bamboo Jaw Harp)',
    nameHi: 'गगना',
    nameAs: 'গগনা',
    nameMni: 'গগনা',
    region: 'Assam',
    state: 'Assam',
    emoji: '🎋',
    description: 'Delicate bamboo jaw harp held between teeth and plucked rhythmically during Bihu dance.',
    descriptionHi: 'दांतों के बीच रखकर बजाई जाने वाली बांस की नन्हीं पत्ती।',
    soundPreset: 'gagana',
    family: 'idiophone',
  },
  {
    id: 'khol',
    name: 'Mrindanga / Khol',
    nameHi: 'खोल (मृदंग)',
    nameAs: 'খোল',
    nameMni: 'খোল',
    region: 'Majuli & Satras',
    state: 'Assam',
    emoji: '🪘',
    description: 'Terracotta two-headed drum sacred to the Vaishnavite Satras of Assam.',
    descriptionHi: 'सत्रों में कीर्तन और भोरताल नृत्य के साथ बजने वाला मिट्टी का मृदंग।',
    soundPreset: 'khol',
    family: 'percussion',
  },
  {
    id: 'bhor_taal',
    name: 'Bhor Taal (Large Cymbals)',
    nameHi: 'भोर ताल',
    nameAs: 'ভোৰতাল',
    nameMni: 'ভোৰ তাল',
    region: 'Barpeta & Satras',
    state: 'Assam',
    emoji: '🔔',
    description: 'Large resonant bell-metal cymbals used in energetic Satriya prayer dances.',
    descriptionHi: 'कांस्य धातु से बने बड़े और गूंजदार मंजीरे/झांझ।',
    soundPreset: 'bhor_taal',
    family: 'idiophone',
  },

  // MEGHALAYA (Khasi / Garo / Jaintia)
  {
    id: 'wangala',
    name: 'Wangala Drum (Dama)',
    nameHi: 'वांगला ढोल (दामा)',
    nameAs: 'ৱাংগালা ঢোল',
    nameMni: 'ৱাংগালা দ্রুম',
    region: 'Garo Hills',
    state: 'Meghalaya',
    emoji: '🥁',
    description: 'Long wooden barrel drum central to the Garo 100-Drums Harvest Festival.',
    descriptionHi: 'गारो पहाड़ियों का लंबा लकड़ी का ढोल जो फसल उत्सव में बजता है।',
    soundPreset: 'wangala',
    family: 'percussion',
  },
  {
    id: 'tangmuri',
    name: 'Ka Tangmuri',
    nameHi: 'का तांगमुरी',
    nameAs: 'টাংমুৰী',
    nameMni: 'তাংমুরী',
    region: 'Khasi & Jaintia Hills',
    state: 'Meghalaya',
    emoji: '🎺',
    description: 'Conical wooden shawm of the Khasi people used during Ka Shad Suk Mynsiem.',
    descriptionHi: 'खासी समुदाय का शहनाई जैसा पवित्र काष्ठ वाद्य।',
    soundPreset: 'tangmuri',
    family: 'wind',
  },
  {
    id: 'singphong',
    name: 'Singphong (Bamboo Slit Zither)',
    nameHi: 'सिंगफोंग',
    nameAs: 'চিংফং',
    nameMni: 'শিংফোং',
    region: 'Khasi Hills',
    state: 'Meghalaya',
    emoji: '🪵',
    description: 'Plucked bamboo tube instrument with cut-out strings made from the bamboo skin.',
    descriptionHi: 'बांस के तने से छीलकर बनाए गए तारों वाला प्राकृतिक वाद्य।',
    soundPreset: 'singphong',
    family: 'string',
  },
  {
    id: 'dama',
    name: 'Kram / Dama Drum',
    nameHi: 'कराम ड्रम',
    nameAs: 'দাম ড্ৰাম',
    nameMni: 'দাম দ্রুম',
    region: 'Garo Hills',
    state: 'Meghalaya',
    emoji: '🪘',
    description: 'Sacred large Garo ceremonial drum played for invoking harvest blessings.',
    descriptionHi: 'गारो संस्कृति का बड़ा अनुष्ठानिक ढोल।',
    soundPreset: 'dama',
    family: 'percussion',
  },
  {
    id: 'maryngod',
    name: 'Duitara / Maryngod',
    nameHi: 'दुईतारा',
    nameAs: 'ডুইতাৰা',
    nameMni: 'দুইতারা',
    region: 'Khasi Hills',
    state: 'Meghalaya',
    emoji: '🎻',
    description: 'Traditional 4-string plucked lute carved from Jackfruit wood with animal skin soundboard.',
    descriptionHi: 'कटहल की लकड़ी से बना खासी लोकगीतों का चार तारों वाला वाद्य।',
    soundPreset: 'maryngod',
    family: 'string',
  },

  // MANIPUR
  {
    id: 'pena',
    name: 'Pena (Bowed Lute)',
    nameHi: 'पेना (सारंगी)',
    nameAs: 'পেনা',
    nameMni: 'ꯄꯦꯅꯥ (Pena)',
    region: 'Imphal Valley',
    state: 'Manipur',
    emoji: '🎻',
    description: 'Sacred single-string bowed fiddle played by balladeers during Lai Haraoba.',
    descriptionHi: 'लाई हरोबा उत्सव में बजाई जाने वाली मणिपुर की पारंपरिक सारंगी।',
    soundPreset: 'pena',
    family: 'string',
  },
  {
    id: 'pung',
    name: 'Pung (Manipuri Drum)',
    nameHi: 'पुंग (मणिपुरी ढोल)',
    nameAs: 'পুং',
    nameMni: 'ꯄꯨꯡ (Pung)',
    region: 'Manipur Valley',
    state: 'Manipur',
    emoji: '🪘',
    description: 'Graceful clay and wood cylindrical drum played during the acrobatic Pung Cholom dance.',
    descriptionHi: 'पुंग चोलोम नृत्य में बजाया जाने वाला सुरुचिपूर्ण मृदंग।',
    soundPreset: 'pung',
    family: 'percussion',
  },
  {
    id: 'khartal',
    name: 'Khartal (Hand Cymbals)',
    nameHi: 'करताल',
    nameAs: 'কৰতাল',
    nameMni: 'ꯈꯔꯇꯥꯜ (Khartal)',
    region: 'Manipur Valley',
    state: 'Manipur',
    emoji: '🔔',
    description: 'Hand-held brass cymbals with colored ribbons played in Sankirtana chanting.',
    descriptionHi: 'संकीर्तन में लय साधने के लिए बजाई जाने वाली रंगीन झांझ।',
    soundPreset: 'khartal',
    family: 'idiophone',
  },

  // MIZORAM
  {
    id: 'khuang',
    name: 'Khuang (Mizo Drum)',
    nameHi: 'ख्वांग (मिज़ो ढोल)',
    nameAs: 'খুয়াং',
    nameMni: 'খুয়াং',
    region: 'Mizo Hills',
    state: 'Mizoram',
    emoji: '🥁',
    description: 'Hollowed tree-trunk drum that is the soul of all Mizo festivals and community dances.',
    descriptionHi: 'मिज़ोरम का मुख्य ढोल, जिसके बिना चापचार कुत उत्सव अधूरा है।',
    soundPreset: 'khuang',
    family: 'percussion',
  },
  {
    id: 'rawchhem',
    name: 'Rawchhem (Bamboo Reed Organ)',
    nameHi: 'रावछेम (बांस का माउथ ऑर्गन)',
    nameAs: 'ৰাওছহেম',
    nameMni: 'রাওছেম',
    region: 'Mizo Hills',
    state: 'Mizoram',
    emoji: '🎍',
    description: 'Unique mouth organ made of 9 graduated bamboo pipes fitted into a dried gourd.',
    descriptionHi: 'सूखे कद्दू में लगी 9 बांस की नलियों वाला पारंपरिक माउथ ऑर्गन।',
    soundPreset: 'rawchhem',
    family: 'wind',
  },
  {
    id: 'darphym',
    name: 'Darphym (Brass Gongs)',
    nameHi: 'दारफिम (कांस्य गोंग)',
    nameAs: 'দাৰফিম',
    nameMni: 'দারফিম',
    region: 'Mizoram',
    state: 'Mizoram',
    emoji: '🔔',
    description: 'Set of brass gongs struck in tuned sequence for ceremonial Khuallam dances.',
    descriptionHi: 'खुल्लम नृत्य में ताल देने वाले सुरीले कांस्य गोंग।',
    soundPreset: 'darphym',
    family: 'idiophone',
  },

  // NAGALAND
  {
    id: 'log_drum',
    name: 'Naga Log Drum',
    nameHi: 'नागा लॉग ड्रम',
    nameAs: 'নাগা কাঠৰ ঢোল',
    nameMni: 'নাগা দ্রুম',
    region: 'Naga Hills (Morung)',
    state: 'Nagaland',
    emoji: '🪵',
    description: 'Monumental carved tree trunk drum beaten with wooden pestles in community Morungs.',
    descriptionHi: 'मोरुंग (सामुदायिक भवन) में रखा विशाल लकड़ी का तना ढोल।',
    soundPreset: 'log_drum',
    family: 'percussion',
  },
  {
    id: 'tati',
    name: 'Tati (Single-String Lute)',
    nameHi: 'ताती (एकतारा)',
    nameAs: 'তাটি',
    nameMni: 'তাতি',
    region: 'Angami & Chakhesang Hills',
    state: 'Nagaland',
    emoji: '🪕',
    description: 'Single-string instrument made of dried gourd and brass wire, singing folk ballads of love and bravery.',
    descriptionHi: 'अंगामी और चाखेसांग जनजाति का सूखा लौकी से बना एकतारा।',
    soundPreset: 'tati',
    family: 'string',
  },
  {
    id: 'petu',
    name: 'Petu (Bowed Fiddle)',
    nameHi: 'पेटू (सारंगी)',
    nameAs: 'পেটু',
    nameMni: 'পেতু',
    region: 'Nagaland Hills',
    state: 'Nagaland',
    emoji: '🎻',
    description: 'Bowed string instrument played by Angami Nagas to accompany melodic folk poems.',
    descriptionHi: 'लोक कविताओं के साथ बजाई जाने वाली नागा सारंगी।',
    soundPreset: 'petu',
    family: 'string',
  },

  // TRIPURA
  {
    id: 'sarinda',
    name: 'Sarinda',
    nameHi: 'सारिंदा',
    nameAs: 'সাৰিন্দা',
    nameMni: 'সারিন্দা',
    region: 'Tripura Hills',
    state: 'Tripura',
    emoji: '🎻',
    description: 'Deep hollow-waisted bowed folk lute of Tripura, known for haunting lyrical melodies.',
    descriptionHi: 'त्रिपुरा की नक्काशीदार सारंगी जो भावपूर्ण धुनें छेड़ती है।',
    soundPreset: 'sarinda',
    family: 'string',
  },
  {
    id: 'kham',
    name: 'Kham Drum',
    nameHi: 'खाम ढोल',
    nameAs: 'খাম ঢোল',
    nameMni: 'খাম',
    region: 'Tripura Hills',
    state: 'Tripura',
    emoji: '🪘',
    description: 'Traditional double-headed wooden drum of the Tipra community played during Garia Puja.',
    descriptionHi: 'गड़िया पूजा और होजागिरी नृत्य में बजने वाला पारंपरिक ढोल।',
    soundPreset: 'kham',
    family: 'percussion',
  },
  {
    id: 'sumui',
    name: 'Sumui (Bamboo Flute)',
    nameHi: 'सुमुई (बांसुरी)',
    nameAs: 'চুমুই বাঁহী',
    nameMni: 'সুমুই',
    region: 'Tripura',
    state: 'Tripura',
    emoji: '🪈',
    description: 'Slender bamboo flute of Tripura with gentle sweet tones.',
    descriptionHi: 'त्रिपुरा की कोमल और मधुर ध्वनि वाली बांसुरी।',
    soundPreset: 'sumui',
    family: 'wind',
  },
  {
    id: 'chongpreng',
    name: 'Chongpreng',
    nameHi: 'चोंगलप्रेन्ग',
    nameAs: 'চংপ্রেং',
    nameMni: 'চংপ্রেং',
    region: 'Tripura',
    state: 'Tripura',
    emoji: '🪕',
    description: 'Plucked bamboo and gourd lute used in evening village gatherings.',
    descriptionHi: 'बांस और सूखी लौकी से बना त्रिपुरा का पारंपरिक तार वाद्य।',
    soundPreset: 'chongpreng',
    family: 'string',
  },

  // ARUNACHAL PRADESH
  {
    id: 'ponung',
    name: 'Ponung Yoksha & Cymbals',
    nameHi: 'पोनुंग झांझ',
    nameAs: 'পনুং তাল',
    nameMni: 'পোনুং',
    region: 'Siang Valley',
    state: 'Arunachal Pradesh',
    emoji: '🔔',
    description: 'Rhythmic sword with hollow hilt containing brass beads, played by the Miri leader during Ponung dance.',
    descriptionHi: 'आदि जनजाति के पोनुंग नृत्य में ताल देने वाली सुरीली तलवार और घंटियाँ।',
    soundPreset: 'ponung',
    family: 'idiophone',
  },
  {
    id: 'jachin',
    name: 'Ja-chin (Bamboo Harp)',
    nameHi: 'जा-चिन (बांस वाद्य)',
    nameAs: 'জা-চিন',
    nameMni: 'জা-চিন',
    region: 'Arunachal Hills',
    state: 'Arunachal Pradesh',
    emoji: '🎋',
    description: 'Delicate bamboo reed instrument of the Nyishi and Adi tribes.',
    descriptionHi: 'निशी और आदि जनजातियों का बांस से बना मधुर वाद्य।',
    soundPreset: 'jachin',
    family: 'idiophone',
  },
  {
    id: 'dranyen',
    name: 'Dranyen (Himalayan Lute)',
    nameHi: 'द्रानयेन (हिमालयी ल्यूट)',
    nameAs: 'দ্ৰানয়েন',
    nameMni: 'দ্রানয়েন',
    region: 'Tawang & West Kameng',
    state: 'Arunachal Pradesh',
    emoji: '🪕',
    description: 'Long-necked fretless 6-string lute with dragon head carving, popular among Monpa and Tibetan traditions.',
    descriptionHi: 'तवांग के मोनपा समुदाय का ड्रैगन नक्काशी वाला छह तारों का वाद्य।',
    soundPreset: 'dranyen',
    family: 'string',
  },

  // SIKKIM
  {
    id: 'gyaling',
    name: 'Gyaling (Monastery Shawm)',
    nameHi: 'ग्यालिंग (मठ का वाद्य)',
    nameAs: 'গ্যালিং',
    nameMni: 'গ্যালিং',
    region: 'Sikkim Monasteries',
    state: 'Sikkim',
    emoji: '🎺',
    description: 'Double-reed monastery instrument made of hardwood and ornate brass bells, blown for morning prayers.',
    descriptionHi: 'सिक्किम के बौद्ध मठों में सुबह की प्रार्थना में बजने वाला वाद्य।',
    soundPreset: 'gyaling',
    family: 'wind',
  },
  {
    id: 'damphu',
    name: 'Damphu Drum',
    nameHi: 'डम्फू ढोल',
    nameAs: 'ডাম্ফু',
    nameMni: 'দাম্ফু',
    region: 'Sikkim Hills',
    state: 'Sikkim',
    emoji: '🥁',
    description: 'Circular wooden frame drum sacred to the Tamang community of Sikkim and hill areas.',
    descriptionHi: 'सिक्किम के तामांग समुदाय का गोल काष्ठ ढोल, जो सेलो गीतों में बजता है।',
    soundPreset: 'damphu',
    family: 'percussion',
  },
  {
    id: 'tungna',
    name: 'Tungna Lute',
    nameHi: 'तुंगना ल्यूट',
    nameAs: 'তুংনা',
    nameMni: 'তুংনা',
    region: 'Sikkim & Darjeeling Hills',
    state: 'Sikkim',
    emoji: '🪕',
    description: 'Plucked wooden folk lute carved from Rhododendron or Jackfruit wood.',
    descriptionHi: 'गुरांस (बुरांश) की लकड़ी से बना सिक्किम का पारंपरिक तार वाद्य।',
    soundPreset: 'tungna',
    family: 'string',
  },

  // CLASSIC INDIAN (FAMILIAR EVERYWHERE)
  {
    id: 'tabla',
    name: 'Tabla',
    nameHi: 'तबला',
    nameAs: 'তবলা',
    nameMni: 'ꯇꯕꯂꯥ (Tabla)',
    region: 'All India',
    state: 'Pan-India',
    emoji: '🪘',
    description: 'Pair of twin hand drums (Dayan and Bayan) providing rhythmic foundation in Indian classical and folk music.',
    descriptionHi: 'भारतीय संगीत का सबसे प्रसिद्ध दायाँ-बायाँ ताल वाद्य।',
    soundPreset: 'tabla',
    family: 'percussion',
  },
  {
    id: 'harmonium',
    name: 'Harmonium',
    nameHi: 'हारमोनियम',
    nameAs: 'হাৰমনিয়াম',
    nameMni: 'ꯍꯥꯔꯃꯣꯅꯤꯌꯝ (Harmonium)',
    region: 'All India',
    state: 'Pan-India',
    emoji: '🎹',
    description: 'Hand-pumped reed organ cherished in every household, temple, and devotional gathering.',
    descriptionHi: 'घर-घर और कीर्तन में बजाया जाने वाला धौंकनी वाला बाजा।',
    soundPreset: 'harmonium',
    family: 'wind',
  },
  {
    id: 'sitar',
    name: 'Sitar',
    nameHi: 'सितार',
    nameAs: 'চিতাৰ',
    nameMni: 'ꯁꯤꯇꯥꯔ (Sitar)',
    region: 'All India',
    state: 'Pan-India',
    emoji: '🪕',
    description: 'Iconic long-necked plucked lute with sympathetic strings and gourd resonator.',
    descriptionHi: 'गूंजदार तारों और तुंबे वाला प्रसिद्ध भारतीय शास्त्रीय वाद्य।',
    soundPreset: 'sitar',
    family: 'string',
  },
  {
    id: 'shehnai',
    name: 'Shehnai',
    nameHi: 'शहनाई',
    nameAs: 'শ্বেহনাই',
    nameMni: 'ꯁꯦꯍꯅꯥꯏ (Shehnai)',
    region: 'All India',
    state: 'Pan-India',
    emoji: '🎺',
    description: 'Auspicious wooden double-reed instrument played during weddings and festive celebrations.',
    descriptionHi: 'शुभ अवसरों और विवाह में बजने वाला मांगलिक वाद्य।',
    soundPreset: 'shehnai',
    family: 'wind',
  },
  {
    id: 'dholak',
    name: 'Dholak',
    nameHi: 'ढोलक',
    nameAs: 'ঢোলক',
    nameMni: 'ꯙꯣꯂꯛ (Dholak)',
    region: 'All India',
    state: 'Pan-India',
    emoji: '🪘',
    description: 'Two-headed folk hand drum popular in family celebrations and festive songs.',
    descriptionHi: 'घर के उत्सवों और लोकगीतों में हाथों से बजाई जाने वाली ढोलक।',
    soundPreset: 'dholak',
    family: 'percussion',
  },
  {
    id: 'ektara',
    name: 'Ektara',
    nameHi: 'एकतारा',
    nameAs: 'একতাৰা',
    nameMni: 'ꯑꯦꯛꯇꯥꯔꯥ (Ektara)',
    region: 'Assam & Bengal',
    state: 'Eastern India',
    emoji: '🪕',
    description: 'Single-string drone instrument played by wandering Bauls and spiritual singers.',
    descriptionHi: 'भक्ति और सूफी गीतों में एक तार से बजाया जाने वाला वाद्य।',
    soundPreset: 'ektara',
    family: 'string',
  },
  {
    id: 'manjira',
    name: 'Manjira / Mandira',
    nameHi: 'मंजीरा',
    nameAs: 'মঞ্জিৰা',
    nameMni: 'ꯃꯟꯖꯤꯔꯥ (Manjira)',
    region: 'All India',
    state: 'Pan-India',
    emoji: '🔔',
    description: 'Small pair of brass clash cymbals giving sweet rhythmic sparkle to morning prayers.',
    descriptionHi: 'प्रार्थना और आरती में मधुर झंकार देने वाले छोटे कांसे के मंजीरे।',
    soundPreset: 'manjira',
    family: 'idiophone',
  },
  {
    id: 'bell',
    name: 'Temple / Prayer Bell',
    nameHi: 'मंदिर की घंटी',
    nameAs: 'মন্দিৰৰ ঘণ্টা',
    nameMni: 'ꯂꯥꯏꯁꯪ ꯘꯟꯇꯥ (Bell)',
    region: 'All Northeast & India',
    state: 'Pan-India',
    emoji: '🔔',
    description: 'Resonant bell that rings across morning hills, temples, and churches.',
    descriptionHi: 'सुबह और शाम की प्रार्थना में बजने वाली पवित्र घंटी।',
    soundPreset: 'bell',
    family: 'idiophone',
  },
]

export const getInstrumentById = (id: string): InstrumentItem | undefined =>
  INSTRUMENT_BANK.find((i) => i.id === id)

export const getInstrumentsByState = (state: string): InstrumentItem[] =>
  INSTRUMENT_BANK.filter((i) => i.state.toLowerCase() === state.toLowerCase())
