export interface LandmarkItem {
  id: string
  name: string
  nameHi: string
  nameAs?: string
  nameMni?: string
  state: string
  emoji: string
  cueQuestion: string
  cueQuestionHi: string
  cueQuestionAs?: string
  clue: string
  clueHi: string
  category: 'river' | 'hills' | 'heritage' | 'sanctuary' | 'monastery' | 'plantation'
}

export const LANDMARKS_BANK: LandmarkItem[] = [
  // ASSAM
  {
    id: 'kaziranga',
    name: 'Kaziranga Grasslands (One-Horned Rhino)',
    nameHi: 'काजीरंगा राष्ट्रीय उद्यान (एक सींग वाला गैंडा)',
    nameAs: 'কাজিৰঙা ৰাষ্ট্ৰীয় উদ্যান',
    nameMni: 'কাজিরঙ্গা',
    state: 'Assam',
    emoji: '🦏',
    cueQuestion: 'Which famous wildlife sanctuary is home to the world-renowned Great One-Horned Rhinoceros?',
    cueQuestionHi: 'कौन सा प्रसिद्ध राष्ट्रीय उद्यान दुनिया भर में एक सींग वाले गैंडे का घर माना जाता है?',
    clue: 'Tall elephant grass by the Brahmaputra floodplains.',
    clueHi: 'ब्रह्मपुत्र नदी के किनारे फैली हरी घास और दलदली भूमि।',
    category: 'sanctuary',
  },
  {
    id: 'brahmaputra_river',
    name: 'Mighty Brahmaputra River (Luit)',
    nameHi: 'ब्रह्मपुत्र नदी (लुइत)',
    nameAs: 'মহাবাহু ব্ৰহ্মপুত্ৰ',
    nameMni: 'ব্রহ্মপুত্র তুরেল',
    state: 'Assam',
    emoji: '🌊',
    cueQuestion: 'Which vast red-water river is revered as the lifeline, soul, and father of Assam?',
    cueQuestionHi: 'असम की जीवनदायिनी और सबसे विशाल नदी कौन सी है जिसे प्यार से "लुइत" भी कहते हैं?',
    clue: 'Vast rolling currents with golden sunsets and freshwater river dolphins.',
    clueHi: 'विशाल पाट, सुनहरी शाम और स्वच्छ पानी की डॉल्फिन वाली नदी।',
    category: 'river',
  },
  {
    id: 'majuli_island',
    name: 'Majuli Island (River Island & Satras)',
    nameHi: 'माजुली द्वीप (दुनिया का सबसे बड़ा नदी द्वीप)',
    nameAs: 'মাজুলী',
    nameMni: 'মাজুলী',
    state: 'Assam',
    emoji: '🏝️',
    cueQuestion: 'Which peaceful river island is world-famous for its Vaishnavite prayer Satras and mask-making art?',
    cueQuestionHi: 'ब्रह्मपुत्र के बीच बसा दुनिया का सबसे बड़ा नदी द्वीप कौन सा है जहाँ सुंदर मुखौटे और भजन होते हैं?',
    clue: 'Quiet island surrounded by water, where Naam Kirtan echoes at sunset.',
    clueHi: 'चारों तरफ पानी से घिरा शांत द्वीप, जहाँ सत्रों में प्रार्थना होती है।',
    category: 'heritage',
  },
  {
    id: 'jorhat_tea_gardens',
    name: 'Tea Gardens of Assam (Rolling Green Slopes)',
    nameHi: 'असम के हरे-भरे चाय बागान',
    nameAs: 'চাহ বাগিচা',
    nameMni: 'চা পাম',
    state: 'Assam',
    emoji: '🍃',
    cueQuestion: 'Which endless green hills are famous worldwide for plucking "two leaves and a bud"?',
    cueQuestionHi: 'दूर-दूर तक फैली मखमली हरी झाड़ियाँ जहाँ चाय की ताज़ी पत्तियाँ चुनी जाती हैं?',
    clue: 'Wicker baskets on workers backs under shady shade trees.',
    clueHi: 'छायादार पेड़ों के नीचे फैली सुगंधित चाय की क्यारियां।',
    category: 'plantation',
  },
  {
    id: 'kamakhya_temple',
    name: 'Kamakhya Hill Temple (Nilachal Hill)',
    nameHi: 'कामाख्या देवी मंदिर (नीलाचल पहाड़ी)',
    nameAs: 'কামাখ্যা মন্দিৰ',
    nameMni: 'কামাখ্যা লাইশং',
    state: 'Assam',
    emoji: '🛕',
    cueQuestion: 'Which ancient sacred hilltop shrine in Guwahati overlooks the Brahmaputra river?',
    cueQuestionHi: 'गुवाहाटी की नीलाचल पहाड़ी पर स्थित प्राचीन और पवित्र शक्तिपीठ मंदिर कौन सा है?',
    clue: 'Stone steps ascending through forest with temple bells ringing.',
    clueHi: 'पहाड़ी की चोटी पर स्थित सुंदर गुंबद और बजती घंटियाँ।',
    category: 'heritage',
  },

  // MEGHALAYA
  {
    id: 'living_root_bridges',
    name: 'Living Root Bridges of Cherrapunji',
    nameHi: 'जीवित जड़ों का पुल (मेघालय)',
    nameAs: 'জীৱন্ত শিপাৰ দলং',
    nameMni: 'লাইভিংস রুট ব্রিজ',
    state: 'Meghalaya',
    emoji: '🌉',
    cueQuestion: 'Which miraculous living bridges are woven across jungle streams from the roots of ancient rubber trees?',
    cueQuestionHi: 'मेघालय के घने जंगलों में पेड़ों की जीवित जड़ों को आपस में गूंथकर कौन से अनोखे पुल बनाए गए हैं?',
    clue: 'Ficus tree roots hand-guided across swift crystal waterfalls.',
    clueHi: 'नदी के ऊपर सालों-साल मजबूत होने वाला प्राकृतिक पुल।',
    category: 'heritage',
  },
  {
    id: 'sohra_waterfalls',
    name: 'Nohkalikai Falls (Sohra Misty Waterfalls)',
    nameHi: 'नोहकालिकाई जलप्रपात (चेरापूंजी का झरना)',
    nameAs: 'নহকালিকাই জলপ্ৰপাত',
    nameMni: 'ঈথক ঝর্ণা',
    state: 'Meghalaya',
    emoji: '🏞️',
    cueQuestion: 'Which dramatic waterfall plunges into a turquoise pool from the green cliffs of Cherrapunji?',
    cueQuestionHi: 'बादलों के घर (मेघालय) में ऊँची हरी पहाड़ियों से नीचे गिरता भव्य जलप्रपात कौन सा है?',
    clue: 'Tall mist rising into cool cloudy mountain air.',
    clueHi: 'बादलों और धुंध के बीच से गिरता गहरा शीतल झरना।',
    category: 'hills',
  },
  {
    id: 'dawki_river',
    name: 'Umngot River at Dawki (Crystal Clear Water)',
    nameHi: 'डावकी की पारदर्शी उमनगोट नदी',
    nameAs: 'ডাউকী নদী',
    nameMni: 'দাউকী তুরেল',
    state: 'Meghalaya',
    emoji: '🛶',
    cueQuestion: 'Which crystal-clear mountain river makes wooden boats look like they are floating in mid-air?',
    cueQuestionHi: 'कांच की तरह एकदम साफ़ पानी वाली नदी, जहाँ नाव हवा में तैरती हुई सी लगती है?',
    clue: 'Smooth pebbles visible at the bottom through glass-like green water.',
    clueHi: 'नदी के तल पर पड़े गोल पत्थर ऊपर से साफ़ चमकते हैं।',
    category: 'river',
  },

  // MANIPUR
  {
    id: 'loktak_lake',
    name: 'Loktak Lake & Floating Islands (Phumdis)',
    nameHi: 'लोकटक झील (तैरते हुए फूमदी द्वीप)',
    nameAs: 'লোকটাক হ্ৰদ',
    nameMni: 'ꯂꯣꯛꯇꯥꯛ ꯄꯥꯠ (Loktak Lake)',
    state: 'Manipur',
    emoji: '🪷',
    cueQuestion: 'Which famous freshwater lake features unique circular floating islands of vegetation (Phumdis)?',
    cueQuestionHi: 'मणिपुर की वह अद्भुत मीठे पानी की झील कौन सी है जिस पर घास के गोल तैरते हुए द्वीप हैं?',
    clue: 'Freshwater lake where dancing Sangai deer walk on floating soil.',
    clueHi: 'नीले पानी पर तैरते प्राकृतिक द्वीप जहाँ शंघाई हिरण रहते हैं।',
    category: 'river',
  },
  {
    id: 'kangla_fort',
    name: 'Kangla Palace & Fort',
    nameHi: 'कांगला किला (इम्फाल)',
    nameAs: 'কাংলা দুৰ্গ',
    nameMni: 'ꯀꯥꯡꯂꯥ (Kangla Fort)',
    state: 'Manipur',
    emoji: '🏛️',
    cueQuestion: 'Which ancient historic royal seat in the heart of Imphal was the palace of Manipur kings?',
    cueQuestionHi: 'इम्फाल के मध्य में स्थित मणिपुर के राजाओं का ऐतिहासिक राजमहल और किला कौन सा है?',
    clue: 'Majestic red stone arches with guardian dragon statues (Kangla Sha).',
    clueHi: 'कांगला शा (पवित्र ड्रैगन) की मूर्तियों वाला ऐतिहासिक राजमहल।',
    category: 'heritage',
  },
  {
    id: 'ima_keithel',
    name: 'Ima Keithel (Mother Market of Imphal)',
    nameHi: 'इमा कैथेल (माताओं का बाज़ार)',
    nameAs: 'ইমা কেইথেল',
    nameMni: 'ꯏꯃꯥ ꯀꯩꯊꯦꯜ (Ima Keithel)',
    state: 'Manipur',
    emoji: '🧺',
    cueQuestion: 'Which famous 500-year-old market in Imphal is run entirely by thousands of proud mothers and women?',
    cueQuestionHi: 'दुनिया का सबसे बड़ा बाज़ार जो केवल माताओं और महिलाओं द्वारा संचालित किया जाता है?',
    clue: 'Bustling covered halls filled with handloom textiles, fresh flowers, and vegetables.',
    clueHi: 'सुंदर हथकरघा साड़ियों और ताज़े फलों से भरा ऐतिहासिक बाज़ार।',
    category: 'heritage',
  },

  // MIZORAM
  {
    id: 'champhai_valley',
    name: 'Champhai Valley (Rice Bowl of Mizoram)',
    nameHi: 'चम्फाई घाटी (मिज़ोरम का धान का कटोरा)',
    nameAs: 'চাম্ফাই উপত্যকা',
    nameMni: 'চাম্ফাই',
    state: 'Mizoram',
    emoji: '🌾',
    cueQuestion: 'Which vast flat green valley nestled among blue hills is known as the "Rice Bowl of Mizoram"?',
    cueQuestionHi: 'नीली पहाड़ियों से घिरी हरी-भरी घाटी जिसे "मिज़ोरम का अन्न का कटोरा" कहते हैं?',
    clue: 'Neat checkerboard paddy fields stretching to the blue mountain horizon.',
    clueHi: 'पहाड़ियों के बीच फैले धान के सुंदर समतल खेत।',
    category: 'hills',
  },
  {
    id: 'reiek_tlang',
    name: 'Reiek Heritage Hill Peak',
    nameHi: 'रेक पहाड़ी (पारंपरिक मिज़ो गाँव)',
    nameAs: 'ৰেইয়েক শৃংগ',
    nameMni: 'রেয়েক',
    state: 'Mizoram',
    emoji: '⛰️',
    cueQuestion: 'Which iconic hill peak offers breathtaking views of the clouds and preserves traditional Mizo thatched huts?',
    cueQuestionHi: 'बादलों से ऊपर उठी वह सुंदर पहाड़ी चोटी जहाँ पारंपरिक मिज़ो घर बने हुए हैं?',
    clue: 'High cliff overlooking rolling green mist and bamboo forests.',
    clueHi: 'ऊँची पहाड़ी की चोटी जहाँ से चारों तरफ बादलों की चादर दिखती है।',
    category: 'hills',
  },

  // NAGALAND
  {
    id: 'dzukou_valley',
    name: 'Dzukou Valley (Valley of Flowers)',
    nameHi: 'ज़ुको घाटी (फूलों की हरी घाटी)',
    nameAs: 'জুকৌ উপত্যকা',
    nameMni: 'জুকৌ ভ্যালী',
    state: 'Nagaland',
    emoji: '🌸',
    cueQuestion: 'Which high-altitude emerald valley on the Nagaland border blooms with rare pink Dzukou lilies in monsoon?',
    cueQuestionHi: 'नागालैंड और मणिपुर की सीमा पर स्थित वह मनमोहक हरी घाटी जहाँ दुर्लभ गुलाबी लिली खिलती हैं?',
    clue: 'Rolling wavy green hills that look like a soft velvet blanket.',
    clueHi: 'मखमली हरी लहरदार पहाड़ियाँ और बहते छोटे झरने।',
    category: 'hills',
  },
  {
    id: 'kohima_war_cemetery',
    name: 'Kohima Memorial Garden',
    nameHi: 'कोहिमा शांति स्मारक उद्यान',
    nameAs: 'কোহিমা স্মৃতি উদ্যান',
    nameMni: 'কোহিমা মেমোরিয়াল',
    state: 'Nagaland',
    emoji: '🌺',
    cueQuestion: 'Which serene hillside floral garden in Kohima honors peace with its famous cherry blossom trees?',
    cueQuestionHi: 'कोहिमा की शांत पहाड़ी पर स्थित सुंदर फूलों और चेरी ब्लॉसम से सजा शांति स्मारक कौन सा है?',
    clue: 'Manicured terraces overlooking the misty capital town.',
    clueHi: 'सुंदर हरी क्यारियां जहाँ शांति और सुकून मिलता है।',
    category: 'heritage',
  },

  // TRIPURA
  {
    id: 'ujjayanta_palace',
    name: 'Ujjayanta White Palace (Agartala)',
    nameHi: 'उज्जयंत राजमहल (अगरतला का श्वेत महल)',
    nameAs: 'উজ্জয়ন্ত প্ৰসাদ',
    nameMni: 'উজ্জয়ন্তা প্যালেস',
    state: 'Tripura',
    emoji: '🏰',
    cueQuestion: 'Which dazzling white palace in Agartala features tiled fountains and Mughal-style garden lakes?',
    cueQuestionHi: 'अगरतला का चमकदार सफेद राजमहल जो सुंदर फव्वारों और झीलों के बीच बना है?',
    clue: 'Grand white domes mirrored in royal garden waters.',
    clueHi: 'सफेद संगमरमरी गुंबद और आगे फैले शांत तालाब।',
    category: 'heritage',
  },
  {
    id: 'neermahal_water_palace',
    name: 'Neermahal (Twijilikma Water Palace)',
    nameHi: 'नीरमहल (झील के बीच बना जल महल)',
    nameAs: 'নীৰমহল',
    nameMni: 'নীরমহল',
    state: 'Tripura',
    emoji: '🏛️',
    cueQuestion: 'Which fairytale red-and-white palace sits right in the middle of Rudrasagar Lake in Tripura?',
    cueQuestionHi: 'रुद्रसागर झील के शांत पानी के बिल्कुल बीचों-बीच बना हुआ जल महल कौन सा है?',
    clue: 'Reached only by graceful wooden rowboats across the lake.',
    clueHi: 'झील में नाव से पहुँचने वाला अनोखा जल महल।',
    category: 'heritage',
  },
  {
    id: 'unakoti_rock_carvings',
    name: 'Unakoti Rock-Cut Bas-Reliefs',
    nameHi: 'उनाकोटी (पहाड़ पर उकेरी गई विशाल मूर्तियाँ)',
    nameAs: 'উনাকোটি',
    nameMni: 'উনাকোতি',
    state: 'Tripura',
    emoji: '🗿',
    cueQuestion: 'Which mysterious forested hillside is famous for hundreds of giant rock-carved deity faces and waterfalls?',
    cueQuestionHi: 'त्रिपुरा की वह पहाड़ी जहाँ चट्टानों को तराशकर विशाल चेहरे और झरने बनाए गए हैं?',
    clue: 'Giant carved stone faces smiling peacefully amid deep green forest.',
    clueHi: 'जंगल के बीच चट्टानों पर तराशी गई प्राचीन सुंदर आकृतियाँ।',
    category: 'heritage',
  },

  // ARUNACHAL PRADESH
  {
    id: 'tawang_monastery',
    name: 'Tawang Monastery (Galden Namgey Lhatse)',
    nameHi: 'तवांग महाविहार (तवांग बौद्ध मठ)',
    nameAs: 'তাৱাং মঠ',
    nameMni: 'তাৱাং লাইশং',
    state: 'Arunachal Pradesh',
    emoji: '🛕',
    cueQuestion: 'Which grand golden monastery perched high on a Himalayan mountain ridge is the largest in India?',
    cueQuestionHi: 'बर्फ़ीली चोटियों के बीच बसा भारत का सबसे विशाल और भव्य बौद्ध मठ कौन सा है?',
    clue: 'Golden roofed sanctuary overlooking snow-capped valleys with fluttering prayer flags.',
    clueHi: 'हवा में लहराती रंगीन प्रार्थना पताकाएं और सुनहरी छत।',
    category: 'monastery',
  },
  {
    id: 'sela_pass_lake',
    name: 'Sela Pass & Sela Lake (Snowy Mountains)',
    nameHi: 'सेला दर्रा और सेला झील',
    nameAs: 'চেলা পাছ আৰু হ্ৰদ',
    nameMni: 'সেলা পাস',
    state: 'Arunachal Pradesh',
    emoji: '🏔️',
    cueQuestion: 'Which high Himalayan snowy mountain pass features twin crystal-blue glacial lakes at 13,700 feet?',
    cueQuestionHi: 'बर्फ से ढकी हिमालय की वह ऊँची घाटी जहाँ नीले पानी की शांत झील स्थित है?',
    clue: 'Snow-covered mountain gateway to Tawang with prayer flags fluttering in cold breeze.',
    clueHi: 'सफेद बर्फ से ढकी पहाड़ियाँ और शांत नीली झील।',
    category: 'hills',
  },

  // SIKKIM
  {
    id: 'kangchenjunga_peak',
    name: 'Mount Kangchenjunga (Sacred Snow Peak)',
    nameHi: 'कंचनजंगा पर्वत शिखर (पवित्र हिमशिखर)',
    nameAs: 'কাঞ্চনজংঘা',
    nameMni: 'কাঞ্চনজঙ্ঘা',
    state: 'Sikkim',
    emoji: '🏔️',
    cueQuestion: 'Which world-famous five-peaked mountain is revered as the sacred guardian protector of Sikkim?',
    cueQuestionHi: 'दुनिया का तीसरा सबसे ऊँचा और सिक्किम का पवित्र रक्षक माना जाने वाला बर्फीला पर्वत कौन सा है?',
    clue: 'Golden morning sunlight touching the world third highest snow peak.',
    clueHi: 'सुबह की पहली सुनहरी धूप से चमकता विशाल बर्फीला पर्वत।',
    category: 'hills',
  },
  {
    id: 'rumtek_monastery',
    name: 'Rumtek Dharma Chakra Monastery',
    nameHi: 'रुमटेक मठ (सिक्किम)',
    nameAs: 'ৰুমটেক মঠ',
    nameMni: 'রুমটেক লাইশং',
    state: 'Sikkim',
    emoji: '🛕',
    cueQuestion: 'Which colourful hilltop monastery near Gangtok is famous for its intricate Tibetan murals and silk thangkas?',
    cueQuestionHi: 'गंगटोक के पास स्थित सुंदर तिब्बती भित्तिचित्रों और सुनहरी मूर्तियों वाला प्रमुख मठ कौन सा है?',
    clue: 'Chanting of monks echoing across prayer wheels on the green hill.',
    clueHi: 'घूमते प्रार्थना चक्र और शांति से भरी मठ की परिक्रमा।',
    category: 'monastery',
  },
  {
    id: 'tsomgo_lake',
    name: 'Tsomgo Glacial Lake (Changu Lake)',
    nameHi: 'त्सोमगो झील (चांगु झील)',
    nameAs: 'চমগো হ্ৰদ',
    nameMni: 'সোমগো পাৎ',
    state: 'Sikkim',
    emoji: '🏞️',
    cueQuestion: 'Which sacred high-altitude alpine lake in Sikkim changes colors with the seasons and reflects snow peaks?',
    cueQuestionHi: 'सिक्किम की ऊँची बर्फीली पहाड़ियों में स्थित वह पवित्र झील जो मौसम के साथ रंग बदलती है?',
    clue: 'Prayer flags around clear cold water where yaks rest on the banks.',
    clueHi: 'झील के किनारे सजे याक और चारों तरफ बर्फ की पहाड़ियाँ।',
    category: 'river',
  },
]
