export interface TraditionalFoodItem {
  id: string
  name: string
  nameHi: string
  nameAs?: string
  nameMni?: string
  state: string
  region: string
  emoji: string
  category: 'sweet' | 'curry' | 'snack' | 'fruit' | 'drink' | 'rice' | 'pickle'
  question: string
  questionHi: string
  culturalNote: string
}

export const TRADITIONAL_FOODS_BANK: TraditionalFoodItem[] = [
  // ASSAM
  {
    id: 'til_pitha',
    name: 'Til Pitha',
    nameHi: 'तिल पीठा',
    nameAs: 'তিল পিঠা',
    nameMni: 'তিল পিথা',
    state: 'Assam',
    region: 'Assam',
    emoji: '🥖',
    category: 'sweet',
    question: 'Which one is the famous crispy roasted rice roll stuffed with sweet black sesame and jaggery?',
    questionHi: 'काले तिल और गुड़ से भरा हुआ कौन सा पारंपरिक कुरकुरा पीठा है?',
    culturalNote: 'Celebratory sweet prepared during Magh and Bohag Bihu festivals.',
  },
  {
    id: 'masor_tenga',
    name: 'Masor Tenga (Tangy Fish Curry)',
    nameHi: 'माछोर टेंगा (खट्टी मछली की तरी)',
    nameAs: 'মাছৰ টেঙা',
    nameMni: 'ঙা থোংবা',
    state: 'Assam',
    region: 'Brahmaputra Valley',
    emoji: '🍲',
    category: 'curry',
    question: 'Which light, refreshing sour fish curry is made with fresh tomatoes and Kaji Nemu lemon?',
    questionHi: 'टमाटर और काज़ी नींबू के रस से बनी हल्की और खट्टी मछली की तरी कौन सी है?',
    culturalNote: 'Beloved soothing summer dish that aids digestion.',
  },
  {
    id: 'jolpan_kumol',
    name: 'Jolpan with Kumol Saul & Curd',
    nameHi: 'जोलपान (कोमल चावल और दही)',
    nameAs: 'কোমল চাউলৰ জলপান',
    nameMni: 'জোলপান',
    state: 'Assam',
    region: 'Assam',
    emoji: '🥣',
    category: 'snack',
    question: 'Which traditional breakfast requires no cooking — simply soaking magic soft rice with creamy curd and jaggery?',
    questionHi: 'बिना पकाए केवल पानी में भिगोकर दही और गुड़ के साथ खाया जाने वाला कोमल चावल कौन सा है?',
    culturalNote: 'Traditional breakfast served to honored morning visitors.',
  },
  {
    id: 'kaji_nemu',
    name: 'Assam Kaji Nemu (Oblong Lemon)',
    nameHi: 'काज़ी नींबू (असमिया नींबू)',
    nameAs: 'কাজী নেমু',
    nameMni: 'চম্প্ৰা',
    state: 'Assam',
    region: 'Assam',
    emoji: '🍋',
    category: 'fruit',
    question: 'Which long, aromatic, seedless green lemon is served with every Assamese lunch thali?',
    questionHi: 'हर दोपहर की थाली में स्वाद और खुशबू बढ़ाने वाला असम का प्रसिद्ध हरा नींबू कौन सा है?',
    culturalNote: 'GI-tagged jewel of Assam, rich in fragrant essential oils.',
  },
  {
    id: 'khar_dish',
    name: 'Omita Khar (Alkaline Papaya Dish)',
    nameHi: 'खार (कच्चे पपीते का खार)',
    nameAs: 'অমিতাৰ খাৰ',
    nameMni: 'খার',
    state: 'Assam',
    region: 'Assam',
    emoji: '🍲',
    category: 'curry',
    question: 'Which gentle digestive starter dish is cooked with traditional sun-dried banana peel ash extract (Khar)?',
    questionHi: 'केले के छिलके से बने प्राकृतिक क्षार के साथ पकाई जाने वाली असमिया भोजन की पहली डिश कौन सी है?',
    culturalNote: 'The hallmark starter that opens an authentic Assamese meal.',
  },

  // MANIPUR
  {
    id: 'chak_hao_kheer',
    name: 'Chak-Hao (Black Rice Kheer)',
    nameHi: 'चक-हाओ (काले चावल की खीर)',
    nameAs: 'চাক-হাও ক্ষীৰ',
    nameMni: 'ꯆꯥꯛ-ꯍꯥꯎ ꯈꯤꯔ',
    state: 'Manipur',
    region: 'Manipur Valley',
    emoji: '🍧',
    category: 'sweet',
    question: 'Which royal purple sweet pudding is made from Manipur naturally aromatic black glutinous rice?',
    questionHi: 'मणिपुर के खुशबूदार काले चावल और दूध से बनने वाली जामुनी रंग की स्वादिष्ट खीर कौन सी है?',
    culturalNote: 'Antioxidant-rich ceremonial dessert served at celebrations.',
  },
  {
    id: 'singju_salad',
    name: 'Singju Salad',
    nameHi: 'सिंगजू (मणिपुरी ताज़ा सलाद)',
    nameAs: 'চিংজু চালাড',
    nameMni: 'ꯁꯤꯡꯖꯨ (Singju)',
    state: 'Manipur',
    region: 'Manipur',
    emoji: '🥗',
    category: 'snack',
    question: 'Which zesty, spicy afternoon salad mixes fresh lotus stems, cabbage, perilla seeds, and herbs?',
    questionHi: 'कमल ककड़ी, पत्तागोभी और सुगंधित जड़ी-बूटियों से बना ताज़ा चटपटा मणिपुरी सलाद कौन सा है?',
    culturalNote: 'Healthy community salad enjoyed in every Meitei household.',
  },
  {
    id: 'kangsoi',
    name: 'Kangsoi (Vegetable Stew)',
    nameHi: 'कांगसोई (सब्ज़ी का सूप)',
    nameAs: 'কাংচই',
    nameMni: 'ꯀꯥꯡꯁꯣꯏ (Kangsoi)',
    state: 'Manipur',
    region: 'Manipur',
    emoji: '🍲',
    category: 'curry',
    question: 'Which light boiled vegetable stew seasoned with ginger, onion, and fresh herbs is loved in Manipur?',
    questionHi: 'बिना तेल के अदरक और हरी पत्तियों के साथ उबाला गया हल्का और पौष्टिक सूप कौन सा है?',
    culturalNote: 'Wholesome everyday stew served with steaming white rice.',
  },

  // MEGHALAYA
  {
    id: 'pukhlein',
    name: 'Pukhlein (Khasi Sweet Bread)',
    nameHi: 'पुखलीन (खासी मीठा पूड़ा)',
    nameAs: 'পুখলিন',
    nameMni: 'পুখলিন',
    state: 'Meghalaya',
    region: 'Khasi Hills',
    emoji: '🍘',
    category: 'sweet',
    question: 'Which golden, crispy sweet fried patty is made of rice flour and jaggery in Meghalaya?',
    questionHi: 'चावल के आटे और गुड़ से बना मेघालय का गोल सुनहरा मीठा स्नैक कौन सा है?',
    culturalNote: 'Favorite teatime snack in Shillong and Khasi homes.',
  },
  {
    id: 'tungrymbai',
    name: 'Tungrymbai (Fermented Soybean Chutney)',
    nameHi: 'टुंगरिम्बाई (सोयाबीन की चटनी)',
    nameAs: 'টুংৰিম্বাই',
    nameMni: 'তুংরিম্বাই',
    state: 'Meghalaya',
    region: 'Khasi & Jaintia Hills',
    emoji: '🫘',
    category: 'pickle',
    question: 'Which warming, aromatic chutney is cooked with naturally fermented soybeans and black sesame?',
    questionHi: 'फर्मेंटेड सोयाबीन और काले तिल से बनी मेघालय की गर्मागर्म पारंपरिक चटनी कौन सी है?',
    culturalNote: 'Winter comfort food providing warmth in the cool misty hills.',
  },
  {
    id: 'khasi_mandarin',
    name: 'Khasi Mandarin Orange',
    nameHi: 'खासी संतरा (मीठा संतरा)',
    nameAs: 'খাছী সুমথিৰা',
    nameMni: 'কমলꯥ',
    state: 'Meghalaya',
    region: 'Sohra & Jaintia Hills',
    emoji: '🍊',
    category: 'fruit',
    question: 'Which sweet, thin-skinned orange grows in the sunny orchards of Sohra and Cherrapunji?',
    questionHi: 'मेघालय की पहाड़ियों का प्रसिद्ध मीठा, रसीला और पतले छिलके वाला संतरा कौन सा है?',
    culturalNote: 'Celebrated GI-certified citrus fruit of Northeast India.',
  },

  // MIZORAM
  {
    id: 'bai_stew',
    name: 'Mizo Bai (Herbal Vegetable Stew)',
    nameHi: 'मिज़ो बाई (सब्जियों का शोरबा)',
    nameAs: 'বাই চুপ',
    nameMni: 'বাই',
    state: 'Mizoram',
    region: 'Mizoram',
    emoji: '🥦',
    category: 'curry',
    question: 'Which comforting vegetable soup is boiled with local mountain greens, bamboo shoots, and baking soda?',
    questionHi: 'ताज़ी हरी पत्तियों और बांस के करील से उबाला गया मिज़ोरम का पारंपरिक सूप कौन सा है?',
    culturalNote: 'Hearty, oil-free everyday dish in Mizo cuisine.',
  },
  {
    id: 'sawhchiar',
    name: 'Sawhchiar (Mizo Rice Porridge)',
    nameHi: 'सौहचियार (मिज़ो खिचड़ी)',
    nameAs: 'সাওহচিয়াৰ',
    nameMni: 'সৌহচিয়ার',
    state: 'Mizoram',
    region: 'Mizoram',
    emoji: '🍲',
    category: 'rice',
    question: 'Which slow-cooked, wholesome rice porridge is prepared during community feasts and gatherings?',
    questionHi: 'उत्सवों में चावल और जड़ी-बूटियों को धीमी आंच पर पकाकर बनाई जाने वाली स्वादिष्ट खिचड़ी कौन सी है?',
    culturalNote: 'Traditional comfort food for family reunions.',
  },

  // NAGALAND
  {
    id: 'axone_dish',
    name: 'Axone / Akhuni (Fermented Soya)',
    nameHi: 'अक्सोने (अखूनी)',
    nameAs: 'আখুনি',
    nameMni: 'ꯑꯈꯨꯅꯤ',
    state: 'Nagaland',
    region: 'Naga Hills',
    emoji: '🫘',
    category: 'pickle',
    question: 'Which iconic fermented soybean preparation gives deep earthy flavor to Naga stews and chutneys?',
    questionHi: 'नागालैंड के हर घर में स्वाद और महक देने वाला सोयाबीन का पारंपरिक फर्मेंटेड पेस्ट कौन सा है?',
    culturalNote: 'Essential culinary staple of Sumi and Naga kitchens.',
  },
  {
    id: 'naga_king_chilli',
    name: 'Naga King Chilli (Bhut Jolokia / Raja Mircha)',
    nameHi: 'राजा मिर्चा (भूत जोलोकिया)',
    nameAs: 'ভোট জলকীয়া',
    nameMni: 'ꯎ-ꯃꯣꯔꯣꯛ',
    state: 'Nagaland',
    region: 'Nagaland',
    emoji: '🌶️',
    category: 'pickle',
    question: 'Which fiery red, highly aromatic pepper is one of the world most famous natural chillies?',
    questionHi: 'दुनिया की सबसे प्रसिद्ध और अत्यंत सुगंधित लाल राजा मिर्च कौन सी है?',
    culturalNote: 'Prized for its intense fruity aroma and medicinal warmth.',
  },

  // TRIPURA
  {
    id: 'muya_awandru',
    name: 'Muya Awandru (Bamboo Shoot Gravy)',
    nameHi: 'मुया अवांद्रू (बांस करील करी)',
    nameAs: 'মুয়া আৱানড্ৰু',
    nameMni: 'মুয়া',
    state: 'Tripura',
    region: 'Tripura',
    emoji: '🎍',
    category: 'curry',
    question: 'Which creamy, comforting bamboo shoot broth thickened with rice flour paste is a pride of Tripura?',
    questionHi: 'चावल के घोल और ताज़े बांस के करील से बनी त्रिपुरा की पौष्टिक कढ़ी कौन सी है?',
    culturalNote: 'Staple dish of the indigenous Tripuri community.',
  },
  {
    id: 'chakhwi',
    name: 'Chakhwi (Tripuri Alkaline Stew)',
    nameHi: 'चाखवी',
    nameAs: 'চাখৱী',
    nameMni: 'চাখবী',
    state: 'Tripura',
    region: 'Tripura',
    emoji: '🍲',
    category: 'curry',
    question: 'Which delicious stew is cooked using natural alkaline Khar and local green jackfruit?',
    questionHi: 'कच्चे कटहल और पपीते के साथ बनाई जाने वाली त्रिपुरा की पारंपरिक सब्जी कौन सी है?',
    culturalNote: 'Nutritious everyday preparation without excessive spices.',
  },

  // ARUNACHAL PRADESH
  {
    id: 'thukpa_noodle',
    name: 'Monpa Thukpa (Noodle Soup)',
    nameHi: 'थुकपा (गर्म नूडल सूप)',
    nameAs: 'থুকপা',
    nameMni: 'ꯊꯨꯛꯄꯥ',
    state: 'Arunachal Pradesh',
    region: 'Tawang & West Kameng',
    emoji: '🍜',
    category: 'curry',
    question: 'Which piping-hot vegetable noodle soup warms chilly evenings in Tawang and the Himalayas?',
    questionHi: 'सर्द मौसम में शरीर को गर्माहट देने वाला पहाड़ों का प्रसिद्ध नूडल सूप कौन सा है?',
    culturalNote: 'Comforting Himalayan soup enjoyed across Monpa homes.',
  },
  {
    id: 'zan_finger_millet',
    name: 'Zan (Millet Porridge)',
    nameHi: 'ज़ान (मंडुआ / रागी का दलिया)',
    nameAs: 'যান',
    nameMni: 'জান',
    state: 'Arunachal Pradesh',
    region: 'Arunachal Pradesh',
    emoji: '🥣',
    category: 'snack',
    question: 'Which wholesome mountain porridge is prepared by boiling roasted finger millet flour with vegetables?',
    questionHi: 'रागी (मंडुआ) के भुने आटे और सब्जियों से बनाया जाने वाला सेहतमंद दलिया कौन सा है?',
    culturalNote: 'Nutritious traditional breakfast for energy and longevity.',
  },

  // SIKKIM
  {
    id: 'momos_steamed',
    name: 'Steamed Momos',
    nameHi: 'मोमोज़ (भाप में पकी पोटली)',
    nameAs: 'মমো',
    nameMni: 'ꯃꯣꯃꯣ',
    state: 'Sikkim',
    region: 'Sikkim',
    emoji: '🥟',
    category: 'snack',
    question: 'Which delicious steamed dumplings filled with spiced cabbage and cheese are served with red tomato sauce?',
    questionHi: 'भाप में पकी हुई गोल पोटलियां जो लाल तीखी चटनी के साथ खाई जाती हैं, क्या कहलाती हैं?',
    culturalNote: 'Universal favorite snack across Sikkim and hill stations.',
  },
  {
    id: 'sel_roti',
    name: 'Sel Roti (Ring-Shaped Rice Bread)',
    nameHi: 'सेल रोटी (चावल का मीठा छल्ला)',
    nameAs: 'চেল ৰুটি',
    nameMni: 'সেল রোটি',
    state: 'Sikkim',
    region: 'Sikkim',
    emoji: '🥯',
    category: 'sweet',
    question: 'Which traditional ring-shaped, crispy golden sweet rice bread is prepared during Diwali and festivals?',
    questionHi: 'त्योहारों में चावल के घोल से गोल छल्ले के आकार में तली जाने वाली मीठी रोटी कौन सी है?',
    culturalNote: 'Celebratory festive bread given to visitors as a sign of affection.',
  },
  {
    id: 'chhurpi_cheese',
    name: 'Chhurpi (Yak Milk Cheese)',
    nameHi: 'छुरपी (पहाड़ी पनीर)',
    nameAs: 'ছুৰ্পী',
    nameMni: 'ছুর্পী',
    state: 'Sikkim',
    region: 'Sikkim Himalayas',
    emoji: '🧀',
    category: 'snack',
    question: 'Which traditional hard cheese made from high-altitude milk is cooked into soothing winter soups with fern?',
    questionHi: 'पहाड़ी दूध से बना पारंपरिक चीज़ (पनीर) जिसे सब्ज़ी और सूप में डाला जाता है, क्या कहलाता है?',
    culturalNote: 'Nutritious mountain cheese rich in protein and calcium.',
  },
]
